INSERT INTO INV_LKUP_STATUS (STATUS_ID, CODE, NAME, NAME_ES)
VALUES (INV_LKUP_STATUS_SEQ.nextval, 'ACTIVE', 'Activo', 'Activo');

INSERT INTO INV_LKUP_STATUS (STATUS_ID, CODE, NAME, NAME_ES)
VALUES (INV_LKUP_STATUS_SEQ.nextval, 'INACTIVE', 'Inactiu', 'Inactivo');

INSERT INTO INV_LKUP_STATUS (STATUS_ID, CODE, NAME, NAME_ES)
VALUES (INV_LKUP_STATUS_SEQ.nextval, 'DEPRECATED', 'Deprecado', 'Deprecado');

INSERT INTO INV_CATEGORY (CATEGORY_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, DELETED_AT,
                          DELETED_BY)
VALUES (INV_CATEGORY_SEQ.nextval, 'Gestió Interna', 'Gestión Interna', SYSTIMESTAMP, 'SETUP_SCRIPT', NULL, NULL, NULL,
        NULL);

INSERT INTO INV_CATEGORY_AUD (AUDIT_ID, CATEGORY_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY,
                              DELETED_AT, DELETED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_CATEGORY_AUD_SEQ.nextval, INV_CATEGORY_SEQ.currval, 'Gestió Interna', 'Gestión Interna', SYSTIMESTAMP,
        'SETUP_SCRIPT', NULL, NULL, NULL, NULL, 'INSERT', SYSTIMESTAMP, 'SETUP_SCRIPT');


INSERT INTO INV_CATEGORY (CATEGORY_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, DELETED_AT,
                          DELETED_BY)
VALUES (INV_CATEGORY_SEQ.nextval, 'Atenció al Client', 'Atención al Cliente', SYSTIMESTAMP, 'SETUP_SCRIPT', NULL, NULL,
        NULL, NULL);

INSERT INTO INV_CATEGORY_AUD (AUDIT_ID, CATEGORY_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY,
                              DELETED_AT, DELETED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_CATEGORY_AUD_SEQ.nextval, INV_CATEGORY_SEQ.currval, 'Atenció al Client', 'Atención al Cliente',
        SYSTIMESTAMP, 'SETUP_SCRIPT', NULL, NULL, NULL, NULL, 'INSERT', SYSTIMESTAMP, 'SETUP_SCRIPT');


INSERT INTO INV_CATEGORY (CATEGORY_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, DELETED_AT,
                          DELETED_BY)
VALUES (INV_CATEGORY_SEQ.nextval, 'Core Bancari', 'Core Bancario', SYSTIMESTAMP, 'SETUP_SCRIPT', NULL, NULL, NULL,
        NULL);

INSERT INTO INV_CATEGORY_AUD (AUDIT_ID, CATEGORY_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY,
                              DELETED_AT, DELETED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_CATEGORY_AUD_SEQ.nextval, INV_CATEGORY_SEQ.currval, 'Core Bancari', 'Core Bancario', SYSTIMESTAMP,
        'SETUP_SCRIPT', NULL, NULL, NULL, NULL, 'INSERT', SYSTIMESTAMP, 'SETUP_SCRIPT');


INSERT INTO INV_SYSTEM_TYPE (SYSTEM_TYPE_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, DELETED_AT,
                             DELETED_BY)
VALUES (INV_SYSTEM_TYPE_SEQ.nextval, 'Aplicació Web', 'Web Application', SYSTIMESTAMP, 'SETUP_SCRIPT', NULL, NULL, NULL,
        NULL);

INSERT INTO INV_SYSTEM_TYPE_AUD (AUDIT_ID, SYSTEM_TYPE_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT,
                                 UPDATED_BY, DELETED_AT, DELETED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_SYSTEM_TYPE_AUD_SEQ.nextval, INV_SYSTEM_TYPE_SEQ.currval, 'Aplicació Web', 'Web Application', SYSTIMESTAMP,
        'SETUP_SCRIPT', NULL, NULL, NULL, NULL, 'INSERT', SYSTIMESTAMP, 'SETUP_SCRIPT');


INSERT INTO INV_SYSTEM_TYPE (SYSTEM_TYPE_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, DELETED_AT,
                             DELETED_BY)
VALUES (INV_SYSTEM_TYPE_SEQ.nextval, 'Microservei Rest', 'Microservicio Rest', SYSTIMESTAMP, 'SETUP_SCRIPT', NULL, NULL,
        NULL, NULL);

INSERT INTO INV_SYSTEM_TYPE_AUD (AUDIT_ID, SYSTEM_TYPE_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT,
                                 UPDATED_BY, DELETED_AT, DELETED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_SYSTEM_TYPE_AUD_SEQ.nextval, INV_SYSTEM_TYPE_SEQ.currval, 'Microservei Rest', 'Microservicio Rest',
        SYSTIMESTAMP, 'SETUP_SCRIPT', NULL, NULL, NULL, NULL, 'INSERT', SYSTIMESTAMP, 'SETUP_SCRIPT');


INSERT INTO INV_SYSTEM_TYPE (SYSTEM_TYPE_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, DELETED_AT,
                             DELETED_BY)
VALUES (INV_SYSTEM_TYPE_SEQ.nextval, 'Procés Batch', 'Proceso Batch', SYSTIMESTAMP, 'SETUP_SCRIPT', NULL, NULL, NULL,
        NULL);

INSERT INTO INV_SYSTEM_TYPE_AUD (AUDIT_ID, SYSTEM_TYPE_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT,
                                 UPDATED_BY, DELETED_AT, DELETED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_SYSTEM_TYPE_AUD_SEQ.nextval, INV_SYSTEM_TYPE_SEQ.currval, 'Procés Batch', 'Proceso Batch', SYSTIMESTAMP,
        'SETUP_SCRIPT', NULL, NULL, NULL, NULL, 'INSERT', SYSTIMESTAMP, 'SETUP_SCRIPT');


INSERT INTO INV_FIELD (FIELD_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, DELETED_AT, DELETED_BY)
VALUES (INV_FIELD_SEQ.nextval, 'Finances', 'Finanzas', SYSTIMESTAMP, 'SETUP_SCRIPT', NULL, NULL, NULL, NULL);

INSERT INTO INV_FIELD_AUD (AUDIT_ID, FIELD_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY,
                           DELETED_AT, DELETED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_FIELD_AUD_SEQ.nextval, INV_FIELD_SEQ.currval, 'Finances', 'Finanzas', SYSTIMESTAMP, 'SETUP_SCRIPT', NULL,
        NULL, NULL, NULL, 'INSERT', SYSTIMESTAMP, 'SETUP_SCRIPT');


INSERT INTO INV_FIELD (FIELD_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, DELETED_AT, DELETED_BY)
VALUES (INV_FIELD_SEQ.nextval, 'Recursos Humans', 'Recursos Humanos', SYSTIMESTAMP, 'SETUP_SCRIPT', NULL, NULL, NULL,
        NULL);

INSERT INTO INV_FIELD_AUD (AUDIT_ID, FIELD_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY,
                           DELETED_AT, DELETED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_FIELD_AUD_SEQ.nextval, INV_FIELD_SEQ.currval, 'Recursos Humans', 'Recursos Humanos', SYSTIMESTAMP,
        'SETUP_SCRIPT', NULL, NULL, NULL, NULL, 'INSERT', SYSTIMESTAMP, 'SETUP_SCRIPT');


INSERT INTO INV_FIELD (FIELD_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, DELETED_AT, DELETED_BY)
VALUES (INV_FIELD_SEQ.nextval, 'Logística', 'Logística', SYSTIMESTAMP, 'SETUP_SCRIPT', NULL, NULL, NULL, NULL);

INSERT INTO INV_FIELD_AUD (AUDIT_ID, FIELD_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY,
                           DELETED_AT, DELETED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_FIELD_AUD_SEQ.nextval, INV_FIELD_SEQ.currval, 'Logística', 'Logística', SYSTIMESTAMP, 'SETUP_SCRIPT', NULL,
        NULL, NULL, NULL, 'INSERT', SYSTIMESTAMP, 'SETUP_SCRIPT');

INSERT INTO INV_ADM_UNIT (ADM_UNIT_ID, CODE, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, DELETED_AT,
                          DELETED_BY)
VALUES (INV_ADM_UNIT_SEQ.nextval, 'UAD001', 'Unitat de Tecnologia i Desenvolupament',
        'Unidad de Tecnología y Desarrollo', SYSTIMESTAMP, 'SETUP_SCRIPT', NULL, NULL, NULL, NULL);

INSERT INTO INV_ADM_UNIT_AUD (AUDIT_ID, ADM_UNIT_ID, CODE, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT,
                              UPDATED_BY, DELETED_AT, DELETED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_ADM_UNIT_AUD_SEQ.nextval, INV_ADM_UNIT_SEQ.currval, 'UAD001', 'Unitat de Tecnologia i Desenvolupament',
        'Unidad de Tecnología y Desarrollo', SYSTIMESTAMP, 'SETUP_SCRIPT', NULL, NULL, NULL, NULL, 'INSERT',
        SYSTIMESTAMP, 'SETUP_SCRIPT');


INSERT INTO INV_ADM_UNIT (ADM_UNIT_ID, CODE, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, DELETED_AT,
                          DELETED_BY)
VALUES (INV_ADM_UNIT_SEQ.nextval, 'UAD002', 'Direcció d''Operacions', 'Dirección de Operaciones', SYSTIMESTAMP,
        'SETUP_SCRIPT', NULL, NULL, NULL, NULL);

INSERT INTO INV_ADM_UNIT_AUD (AUDIT_ID, ADM_UNIT_ID, CODE, NAME, NAME_ES, CREATED_AT, CREATED_BY, UPDATED_AT,
                              UPDATED_BY, DELETED_AT, DELETED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_ADM_UNIT_AUD_SEQ.nextval, INV_ADM_UNIT_SEQ.currval, 'UAD002', 'Direcció d''Operacions',
        'Dirección de Operaciones', SYSTIMESTAMP, 'SETUP_SCRIPT', NULL, NULL, NULL, NULL, 'INSERT', SYSTIMESTAMP,
        'SETUP_SCRIPT');


INSERT INTO INV_COMMISSION (COMMISSION_ID, NAME, NAME_ES, EXPEDIENT_NUMBER, APPROVAL_DATE, COMMISSION_TYPE, CREATED_AT,
                            CREATED_BY, UPDATED_AT, UPDATED_BY, DELETED_AT, DELETED_BY)
VALUES (INV_COMMISSION_SEQ.nextval, 'Comissió d''Arquitectura TI', 'Comisión de Arquitectura TI', 'EXP-2026-001',
        TO_DATE('2026-01-10', 'YYYY-MM-DD'), 'TECNICA', SYSTIMESTAMP, 'SETUP_SCRIPT', NULL, NULL, NULL, NULL);

INSERT INTO INV_COMMISSION_AUD (AUDIT_ID, COMMISSION_ID, NAME, NAME_ES, EXPEDIENT_NUMBER, APPROVAL_DATE,
                                COMMISSION_TYPE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, DELETED_AT, DELETED_BY,
                                AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_COMMISSION_AUD_SEQ.nextval, INV_COMMISSION_SEQ.currval, 'Comissió d''Arquitectura TI',
        'Comisión de Arquitectura TI', 'EXP-2026-001', TO_DATE('2026-01-10', 'YYYY-MM-DD'), 'TECNICA', SYSTIMESTAMP,
        'SETUP_SCRIPT', NULL, NULL, NULL, NULL, 'INSERT', SYSTIMESTAMP, 'SETUP_SCRIPT');

INSERT INTO INV_COMMISSION (COMMISSION_ID, NAME, NAME_ES, EXPEDIENT_NUMBER, APPROVAL_DATE, COMMISSION_TYPE, CREATED_AT,
                            CREATED_BY, UPDATED_AT, UPDATED_BY, DELETED_AT, DELETED_BY)
VALUES (INV_COMMISSION_SEQ.nextval, 'Comitè de Seguretat de la Informació', 'Comité de Seguridad de la Información',
        'EXP-2026-002', TO_DATE('2026-01-12', 'YYYY-MM-DD'), 'SUPERIOR', SYSTIMESTAMP, 'SETUP_SCRIPT', NULL, NULL, NULL,
        NULL);

INSERT INTO INV_COMMISSION_AUD (AUDIT_ID, COMMISSION_ID, NAME, NAME_ES, EXPEDIENT_NUMBER, APPROVAL_DATE,
                                COMMISSION_TYPE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, DELETED_AT, DELETED_BY,
                                AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_COMMISSION_AUD_SEQ.nextval, INV_COMMISSION_SEQ.currval, 'Comitè de Seguretat de la Informació',
        'Comité de Seguridad de la Información', 'EXP-2026-002', TO_DATE('2026-01-12', 'YYYY-MM-DD'), 'SUPERIOR',
        SYSTIMESTAMP, 'SETUP_SCRIPT', NULL, NULL, NULL, NULL, 'INSERT', SYSTIMESTAMP, 'SETUP_SCRIPT');


INSERT INTO INV_APPLICATION (APP_APPLICATION_ID, CODE, PREFIX, NAME, CATEGORY_ID, SYSTEM_TYPE_ID,
                             FIELD_ID, ADM_UNIT_ID, COMMISSION_ID, STATUS_ID, DESCRIPTION,
                             CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, EXPIRATION_DATE,
                             DELETED_AT, DELETED_BY)
VALUES (INV_APPLICATION_SEQ.nextval,
        'APP-001',
        'FIN',
        'Sistema de Facturación Electrónica',
        (SELECT CATEGORY_ID FROM INV_CATEGORY WHERE NAME = 'Gestió Interna'),
        (SELECT SYSTEM_TYPE_ID FROM INV_SYSTEM_TYPE WHERE NAME = 'Aplicació Web'),
        (SELECT FIELD_ID FROM INV_FIELD WHERE NAME = 'Finances'),
        (SELECT ADM_UNIT_ID FROM INV_ADM_UNIT WHERE CODE = 'UAD001'),
        (SELECT COMMISSION_ID FROM INV_COMMISSION WHERE NAME = 'Comissió d''Arquitectura TI'),
        (SELECT STATUS_ID FROM INV_LKUP_STATUS WHERE CODE = 'ACTIVE'),
        TO_CLOB('Aplicación principal encargada del procesamiento, firma y envío de facturas electrónicas a la entidad regulatoria.'),
        TO_TIMESTAMP('2026-01-15 09:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        'admin',
        TO_TIMESTAMP('2026-03-01 14:30:00', 'YYYY-MM-DD HH24:MI:SS'),
        'mod_user',
        TO_TIMESTAMP('2030-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        NULL);

INSERT INTO INV_APPLICATION_AUD (AUDIT_ID, APP_APPLICATION_ID, CODE, PREFIX, NAME, CATEGORY_ID,
                                 SYSTEM_TYPE_ID, FIELD_ID, ADM_UNIT_ID, COMMISSION_ID, STATUS_ID, DESCRIPTION,
                                 CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, DELETED_AT, DELETED_BY,
                                 EXPIRATION_DATE, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_APPLICATION_AUD_SEQ.nextval,
        INV_APPLICATION_SEQ.currval,
        'APP-001',
        'FIN',
        'Sistema de Facturación Electrónica',
        (SELECT CATEGORY_ID FROM INV_CATEGORY WHERE NAME = 'Gestió Interna'),
        (SELECT SYSTEM_TYPE_ID FROM INV_SYSTEM_TYPE WHERE NAME = 'Aplicació Web'),
        (SELECT FIELD_ID FROM INV_FIELD WHERE NAME = 'Finances'),
        (SELECT ADM_UNIT_ID FROM INV_ADM_UNIT WHERE CODE = 'UAD001'),
        (SELECT COMMISSION_ID FROM INV_COMMISSION WHERE NAME = 'Comissió d''Arquitectura TI'),
        (SELECT STATUS_ID FROM INV_LKUP_STATUS WHERE CODE = 'ACTIVE'),
        TO_CLOB('Aplicación principal encargada del procesamiento, firma y envío de facturas electrónicas.'),
        TO_TIMESTAMP('2026-01-15 09:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        'admin',
        NULL,
        NULL,
        NULL,
        NULL,
        TO_TIMESTAMP('2030-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'INSERT',
        TO_TIMESTAMP('2026-01-15 09:05:00', 'YYYY-MM-DD HH24:MI:SS'),
        'db_trigger');

INSERT INTO INV_APPLICATION_AUD (AUDIT_ID, APP_APPLICATION_ID, CODE, PREFIX, NAME, CATEGORY_ID,
                                 SYSTEM_TYPE_ID, FIELD_ID, ADM_UNIT_ID, COMMISSION_ID, STATUS_ID, DESCRIPTION,
                                 CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, DELETED_AT, DELETED_BY,
                                 EXPIRATION_DATE, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_APPLICATION_AUD_SEQ.nextval,
        INV_APPLICATION_SEQ.currval,
        'APP-001',
        'FIN',
        'Sistema de Facturación Electrónica',
        (SELECT CATEGORY_ID FROM INV_CATEGORY WHERE NAME = 'Gestió Interna'),
        (SELECT SYSTEM_TYPE_ID FROM INV_SYSTEM_TYPE WHERE NAME = 'Aplicació Web'),
        (SELECT FIELD_ID FROM INV_FIELD WHERE NAME = 'Finances'),
        (SELECT ADM_UNIT_ID FROM INV_ADM_UNIT WHERE CODE = 'UAD001'),
        (SELECT COMMISSION_ID FROM INV_COMMISSION WHERE NAME = 'Comissió d''Arquitectura TI'),
        (SELECT STATUS_ID FROM INV_LKUP_STATUS WHERE CODE = 'ACTIVE'),
        TO_CLOB('Aplicación principal encargada del procesamiento, firma y envío de facturas electrónicas a la entidad regulatoria.'),
        TO_TIMESTAMP('2026-01-15 09:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        'admin',
        TO_TIMESTAMP('2026-03-01 14:30:00', 'YYYY-MM-DD HH24:MI:SS'),
        'mod_user',
        NULL,
        NULL,
        TO_TIMESTAMP('2030-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'UPDATE',
        TO_TIMESTAMP('2026-03-01 14:30:00', 'YYYY-MM-DD HH24:MI:SS'),
        'mod_user');


INSERT INTO INV_APPLICATION (APP_APPLICATION_ID, CODE, PREFIX, NAME, CATEGORY_ID, SYSTEM_TYPE_ID,
                             FIELD_ID, ADM_UNIT_ID, COMMISSION_ID, STATUS_ID, DESCRIPTION,
                             CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, EXPIRATION_DATE,
                             DELETED_AT, DELETED_BY)
VALUES (INV_APPLICATION_SEQ.nextval,
        'APP-002',
        'RRH',
        'Portal del Empleado v2',
        (SELECT CATEGORY_ID FROM INV_CATEGORY WHERE NAME = 'Gestió Interna'),
        (SELECT SYSTEM_TYPE_ID FROM INV_SYSTEM_TYPE WHERE NAME = 'Microservei Rest'),
        (SELECT FIELD_ID FROM INV_FIELD WHERE NAME = 'Recursos Humans'),
        (SELECT ADM_UNIT_ID FROM INV_ADM_UNIT WHERE CODE = 'UAD002'),
        (SELECT COMMISSION_ID FROM INV_COMMISSION WHERE NAME = 'Comitè de Seguretat de la Informació'),
        (SELECT STATUS_ID FROM INV_LKUP_STATUS WHERE CODE = 'INACTIVE'),
        TO_CLOB('API Rest para la autogestión de vacaciones, nóminas y permisos del personal corporativo.'),
        TO_TIMESTAMP('2026-02-10 08:15:00', 'YYYY-MM-DD HH24:MI:SS'),
        'hr_manager',
        NULL,
        NULL,
        TO_TIMESTAMP('2028-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        NULL);

INSERT INTO INV_APPLICATION_AUD (AUDIT_ID, APP_APPLICATION_ID, CODE, PREFIX, NAME, CATEGORY_ID,
                                 SYSTEM_TYPE_ID, FIELD_ID, ADM_UNIT_ID, COMMISSION_ID, STATUS_ID, DESCRIPTION,
                                 CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, DELETED_AT, DELETED_BY,
                                 EXPIRATION_DATE, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_APPLICATION_AUD_SEQ.nextval,
        INV_APPLICATION_SEQ.currval,
        'APP-002',
        'RRH',
        'Portal del Empleado v2',
        (SELECT CATEGORY_ID FROM INV_CATEGORY WHERE NAME = 'Gestió Interna'),
        (SELECT SYSTEM_TYPE_ID FROM INV_SYSTEM_TYPE WHERE NAME = 'Microservei Rest'),
        (SELECT FIELD_ID FROM INV_FIELD WHERE NAME = 'Recursos Humans'),
        (SELECT ADM_UNIT_ID FROM INV_ADM_UNIT WHERE CODE = 'UAD002'),
        (SELECT COMMISSION_ID FROM INV_COMMISSION WHERE NAME = 'Comitè de Seguretat de la Informació'),
        (SELECT STATUS_ID FROM INV_LKUP_STATUS WHERE CODE = 'INACTIVE'),
        TO_CLOB('API Rest para la autogestión de vacaciones, nóminas y permisos del personal corporativo.'),
        TO_TIMESTAMP('2026-02-10 08:15:00', 'YYYY-MM-DD HH24:MI:SS'),
        'hr_manager',
        NULL,
        NULL,
        NULL,
        NULL,
        TO_TIMESTAMP('2028-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        'INSERT',
        TO_TIMESTAMP('2026-02-10 08:15:00', 'YYYY-MM-DD HH24:MI:SS'),
        'db_trigger');

COMMIT;