CREATE UNIQUE INDEX INV_IDENTITY_PROVIDER_PK_I ON INV_IDENTITY_PROVIDER (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_PERS_DATA_PROC_PK_I ON INV_PERSONAL_DATA_PROCESSING (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_WEB_CONTEXT_PK_I ON INV_WEB_CONTEXT (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_LKUP_SECURITY_LEVEL_PK_I ON INV_LKUP_SECURITY_LEVEL (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_LKUP_ENS_SUBJECT_PK_I ON INV_LKUP_ENS_SUBJECT (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_SECURITY_ROLE_PK_I ON INV_SECURITY_ROLE (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_SECURITY_MEASURE_TYPE_PK_I ON INV_SECURITY_MEASURE_TYPE (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_ACCESSIBILITY_COMPL_PK_I ON INV_COMPLIANCE_SITUATION (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_PORTAL_CLASSIF_PK_I ON INV_CLASSIFICATION_SEGMENT (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_ENS_REQUIREMENT_PK_I ON INV_ENS_REQUIREMENT (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_SECURITY_PK_I ON INV_APP_SECURITY (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_ROLE_PK_I ON INV_APP_ROLE (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_WEB_CONTEXT_PK_I ON INV_APP_WEB_CONTEXT (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_ENS_CLASSIF_PK_I ON INV_APP_ENS_CLASSIFICATION (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_SECURITY_RISK_PK_I ON INV_APP_SECURITY_RISK (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_SECURITY_MEAS_PK_I ON INV_APP_SECURITY_MEASURE (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_ACCESSIBILITY_PK_I ON INV_APP_ACCESSIBILITY (ID) TABLESPACE INVAI_INDEX;

CREATE UNIQUE INDEX INV_IDENTITY_PROVIDER_AUD_PK_I ON INV_IDENTITY_PROVIDER_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_PERS_DATA_PROC_AUD_PK_I ON INV_PERS_DATA_PROC_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_WEB_CONTEXT_AUD_PK_I ON INV_WEB_CONTEXT_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_SEC_MEASURE_TYPE_AUD_PK_I ON INV_SECURITY_MEASURE_TYPE_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_ACCESS_COMPL_AUD_PK_I ON INV_COMPLIANCE_SITUATION_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_PORTAL_CLASSIF_AUD_PK_I ON INV_CLASSIFICATION_SEGMENT_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_ENS_REQUIREMENT_AUD_PK_I ON INV_ENS_REQUIREMENT_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_SECURITY_AUD_PK_I ON INV_APP_SECURITY_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_ROLE_AUD_PK_I ON INV_APP_ROLE_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_WEB_CTX_AUD_PK_I ON INV_APP_WEB_CONTEXT_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_ENS_CLASSIF_AUD_PK_I ON INV_APP_ENS_CLASSIFICATION_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_SEC_RISK_AUD_PK_I ON INV_APP_SECURITY_RISK_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_SEC_MEAS_AUD_PK_I ON INV_APP_SECURITY_MEASURE_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_ACCESSIBILITY_AUD_PK_I ON INV_APP_ACCESSIBILITY_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;

CREATE INDEX INV_APP_SECURITY_APP_I ON INV_APP_SECURITY (APPLICATION_ID) TABLESPACE INVAI_INDEX;

CREATE INDEX INV_APP_ROLE_SEC_I ON INV_APP_ROLE (APP_SECURITY_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_ROLE_ROLE_I ON INV_APP_ROLE (SECURITY_ROLE_ID) TABLESPACE INVAI_INDEX;

CREATE INDEX INV_APP_WEB_CTX_SEC_I ON INV_APP_WEB_CONTEXT (APP_SECURITY_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_WEB_CTX_CTX_I ON INV_APP_WEB_CONTEXT (WEB_CONTEXT_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_WEB_CTX_FIELD_I ON INV_APP_WEB_CONTEXT (FIELD_ID) TABLESPACE INVAI_INDEX;

CREATE INDEX INV_APP_ENS_CLASSIF_SEC_I ON INV_APP_ENS_CLASSIFICATION (APP_SECURITY_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_ENS_CLASSIF_IDP_I ON INV_APP_ENS_CLASSIFICATION (IDENTITY_PROVIDER_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_ENS_CLASSIF_SUBJ_I ON INV_APP_ENS_CLASSIFICATION (ENS_SUBJECT_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_ENS_CLASSIF_PDP_I ON INV_APP_ENS_CLASSIFICATION (PERSONAL_DATA_PROCESSING_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_ENS_CLASSIF_CONF_I ON INV_APP_ENS_CLASSIFICATION (CONFIDENTIALITY_LEVEL_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_ENS_CLASSIF_INTG_I ON INV_APP_ENS_CLASSIFICATION (INTEGRITY_LEVEL_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_ENS_CLASSIF_TRAC_I ON INV_APP_ENS_CLASSIFICATION (TRACEABILITY_LEVEL_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_ENS_CLASSIF_AVAIL_I ON INV_APP_ENS_CLASSIFICATION (AVAILABILITY_LEVEL_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_ENS_CLASSIF_AUTH_I ON INV_APP_ENS_CLASSIFICATION (AUTHENTICITY_LEVEL_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_ENS_CLASSIF_GRADE_I ON INV_APP_ENS_CLASSIFICATION (OVERALL_GRADE_LEVEL_ID) TABLESPACE INVAI_INDEX;

CREATE INDEX INV_APP_SEC_RISK_SEC_I ON INV_APP_SECURITY_RISK (APP_SECURITY_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_SEC_RISK_LEVEL_I ON INV_APP_SECURITY_RISK (LEVEL_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_SEC_RISK_FIELD_I ON INV_APP_SECURITY_RISK (FIELD_ID) TABLESPACE INVAI_INDEX;

CREATE INDEX INV_APP_SEC_MEAS_SEC_I ON INV_APP_SECURITY_MEASURE (APP_SECURITY_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_SEC_MEAS_TYPE_I ON INV_APP_SECURITY_MEASURE (TYPE_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_SEC_MEAS_ENSREQ_I ON INV_APP_SECURITY_MEASURE (ENS_REQUIREMENT_ID) TABLESPACE INVAI_INDEX;

CREATE INDEX INV_APP_ACCESSIBILITY_APP_I ON INV_APP_ACCESSIBILITY (APPLICATION_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_ACCESS_COMPL_I ON INV_APP_ACCESSIBILITY (COMPLIANCE_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_ACCESS_PORTAL_CLASS_I ON INV_APP_ACCESSIBILITY (CLASSIFICATION_SEGMENT_ID) TABLESPACE INVAI_INDEX;
