ALTER TABLE INV_IDENTITY_PROVIDER
    ADD CONSTRAINT INV_IDENTITY_PROVIDER_PK PRIMARY KEY (ID) USING INDEX INV_IDENTITY_PROVIDER_PK_I;
ALTER TABLE INV_IDENTITY_PROVIDER_AUD
    ADD CONSTRAINT INV_IDENTITY_PROVIDER_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_IDENTITY_PROVIDER_AUD_PK_I;

ALTER TABLE INV_PERSONAL_DATA_PROCESSING
    ADD CONSTRAINT INV_PERS_DATA_PROC_PK PRIMARY KEY (ID) USING INDEX INV_PERS_DATA_PROC_PK_I;
ALTER TABLE INV_PERS_DATA_PROC_AUD
    ADD CONSTRAINT INV_PERS_DATA_PROC_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_PERS_DATA_PROC_AUD_PK_I;

ALTER TABLE INV_WEB_CONTEXT
    ADD CONSTRAINT INV_WEB_CONTEXT_PK PRIMARY KEY (ID) USING INDEX INV_WEB_CONTEXT_PK_I;
ALTER TABLE INV_WEB_CONTEXT_AUD
    ADD CONSTRAINT INV_WEB_CONTEXT_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_WEB_CONTEXT_AUD_PK_I;

ALTER TABLE INV_LKUP_SECURITY_LEVEL
    ADD CONSTRAINT INV_LKUP_SECURITY_LEVEL_PK PRIMARY KEY (ID) USING INDEX INV_LKUP_SECURITY_LEVEL_PK_I;

ALTER TABLE INV_LKUP_ENS_SUBJECT
    ADD CONSTRAINT INV_LKUP_ENS_SUBJECT_PK PRIMARY KEY (ID) USING INDEX INV_LKUP_ENS_SUBJECT_PK_I;

ALTER TABLE INV_SECURITY_ROLE
    ADD CONSTRAINT INV_SECURITY_ROLE_PK PRIMARY KEY (ID) USING INDEX INV_SECURITY_ROLE_PK_I;

ALTER TABLE INV_SECURITY_MEASURE_TYPE
    ADD CONSTRAINT INV_SEC_MEASURE_TYPE_PK PRIMARY KEY (ID) USING INDEX INV_SECURITY_MEASURE_TYPE_PK_I;
ALTER TABLE INV_SECURITY_MEASURE_TYPE_AUD
    ADD CONSTRAINT INV_SEC_MEASURE_TYPE_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_SEC_MEASURE_TYPE_AUD_PK_I;

ALTER TABLE INV_COMPLIANCE_SITUATION
    ADD CONSTRAINT INV_ACCESSIBILITY_COMPL_PK PRIMARY KEY (ID) USING INDEX INV_ACCESSIBILITY_COMPL_PK_I;
ALTER TABLE INV_COMPLIANCE_SITUATION_AUD
    ADD CONSTRAINT INV_ACCESS_COMPL_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_ACCESS_COMPL_AUD_PK_I;

ALTER TABLE INV_CLASSIFICATION_SEGMENT
    ADD CONSTRAINT INV_PORTAL_CLASSIF_PK PRIMARY KEY (ID) USING INDEX INV_PORTAL_CLASSIF_PK_I;
ALTER TABLE INV_CLASSIFICATION_SEGMENT_AUD
    ADD CONSTRAINT INV_PORTAL_CLASSIF_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_PORTAL_CLASSIF_AUD_PK_I;

ALTER TABLE INV_ENS_REQUIREMENT
    ADD CONSTRAINT INV_ENS_REQUIREMENT_PK PRIMARY KEY (ID) USING INDEX INV_ENS_REQUIREMENT_PK_I;
ALTER TABLE INV_ENS_REQUIREMENT_AUD
    ADD CONSTRAINT INV_ENS_REQUIREMENT_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_ENS_REQUIREMENT_AUD_PK_I;

ALTER TABLE INV_APP_SECURITY
    ADD CONSTRAINT INV_APP_SECURITY_PK PRIMARY KEY (ID) USING INDEX INV_APP_SECURITY_PK_I;
ALTER TABLE INV_APP_SECURITY_AUD
    ADD CONSTRAINT INV_APP_SECURITY_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_SECURITY_AUD_PK_I;

ALTER TABLE INV_APP_ROLE
    ADD CONSTRAINT INV_APP_ROLE_PK PRIMARY KEY (ID) USING INDEX INV_APP_ROLE_PK_I;
ALTER TABLE INV_APP_ROLE_AUD
    ADD CONSTRAINT INV_APP_ROLE_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_ROLE_AUD_PK_I;

ALTER TABLE INV_APP_WEB_CONTEXT
    ADD CONSTRAINT INV_APP_WEB_CONTEXT_PK PRIMARY KEY (ID) USING INDEX INV_APP_WEB_CONTEXT_PK_I;
ALTER TABLE INV_APP_WEB_CONTEXT_AUD
    ADD CONSTRAINT INV_APP_WEB_CTX_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_WEB_CTX_AUD_PK_I;

ALTER TABLE INV_APP_ENS_CLASSIFICATION
    ADD CONSTRAINT INV_APP_ENS_CLASSIF_PK PRIMARY KEY (ID) USING INDEX INV_APP_ENS_CLASSIF_PK_I;
ALTER TABLE INV_APP_ENS_CLASSIFICATION_AUD
    ADD CONSTRAINT INV_APP_ENS_CLASSIF_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_ENS_CLASSIF_AUD_PK_I;

ALTER TABLE INV_APP_SECURITY_RISK
    ADD CONSTRAINT INV_APP_SECURITY_RISK_PK PRIMARY KEY (ID) USING INDEX INV_APP_SECURITY_RISK_PK_I;
ALTER TABLE INV_APP_SECURITY_RISK_AUD
    ADD CONSTRAINT INV_APP_SEC_RISK_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_SEC_RISK_AUD_PK_I;

ALTER TABLE INV_APP_SECURITY_MEASURE
    ADD CONSTRAINT INV_APP_SECURITY_MEAS_PK PRIMARY KEY (ID) USING INDEX INV_APP_SECURITY_MEAS_PK_I;
ALTER TABLE INV_APP_SECURITY_MEASURE_AUD
    ADD CONSTRAINT INV_APP_SEC_MEAS_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_SEC_MEAS_AUD_PK_I;

ALTER TABLE INV_APP_ACCESSIBILITY
    ADD CONSTRAINT INV_APP_ACCESSIBILITY_PK PRIMARY KEY (ID) USING INDEX INV_APP_ACCESSIBILITY_PK_I;
ALTER TABLE INV_APP_ACCESSIBILITY_AUD
    ADD CONSTRAINT INV_APP_ACCESSIBILITY_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_ACCESSIBILITY_AUD_PK_I;

ALTER TABLE INV_APP_SECURITY
    ADD CONSTRAINT INV_APP_SECURITY_APP_FK FOREIGN KEY (APPLICATION_ID) REFERENCES INV_APPLICATION (APP_APPLICATION_ID);

ALTER TABLE INV_APP_ROLE
    ADD CONSTRAINT INV_APP_ROLE_SEC_FK FOREIGN KEY (APP_SECURITY_ID) REFERENCES INV_APP_SECURITY (ID);
ALTER TABLE INV_APP_ROLE
    ADD CONSTRAINT INV_APP_ROLE_ROLE_FK FOREIGN KEY (SECURITY_ROLE_ID) REFERENCES INV_SECURITY_ROLE (ID);

ALTER TABLE INV_APP_WEB_CONTEXT
    ADD CONSTRAINT INV_APP_WEB_CTX_SEC_FK FOREIGN KEY (APP_SECURITY_ID) REFERENCES INV_APP_SECURITY (ID);
ALTER TABLE INV_APP_WEB_CONTEXT
    ADD CONSTRAINT INV_APP_WEB_CTX_CTX_FK FOREIGN KEY (WEB_CONTEXT_ID) REFERENCES INV_WEB_CONTEXT (ID);
ALTER TABLE INV_APP_WEB_CONTEXT
    ADD CONSTRAINT INV_APP_WEB_CTX_FIELD_FK FOREIGN KEY (FIELD_ID) REFERENCES INV_FIELD (FIELD_ID);

ALTER TABLE INV_APP_ENS_CLASSIFICATION
    ADD CONSTRAINT INV_APP_ENS_CLASSIF_SEC_FK FOREIGN KEY (APP_SECURITY_ID) REFERENCES INV_APP_SECURITY (ID);
ALTER TABLE INV_APP_ENS_CLASSIFICATION
    ADD CONSTRAINT INV_APP_ENS_CLASSIF_IDP_FK FOREIGN KEY (IDENTITY_PROVIDER_ID) REFERENCES INV_IDENTITY_PROVIDER (ID);
ALTER TABLE INV_APP_ENS_CLASSIFICATION
    ADD CONSTRAINT INV_APP_ENS_CLASSIF_SUBJ_FK FOREIGN KEY (ENS_SUBJECT_ID) REFERENCES INV_LKUP_ENS_SUBJECT (ID);
ALTER TABLE INV_APP_ENS_CLASSIFICATION
    ADD CONSTRAINT INV_APP_ENS_CLASSIF_PDP_FK FOREIGN KEY (PERSONAL_DATA_PROCESSING_ID) REFERENCES INV_PERSONAL_DATA_PROCESSING (ID);
ALTER TABLE INV_APP_ENS_CLASSIFICATION
    ADD CONSTRAINT INV_APP_ENS_CLASSIF_CONF_FK FOREIGN KEY (CONFIDENTIALITY_LEVEL_ID) REFERENCES INV_LKUP_SECURITY_LEVEL (ID);
ALTER TABLE INV_APP_ENS_CLASSIFICATION
    ADD CONSTRAINT INV_APP_ENS_CLASSIF_INTG_FK FOREIGN KEY (INTEGRITY_LEVEL_ID) REFERENCES INV_LKUP_SECURITY_LEVEL (ID);
ALTER TABLE INV_APP_ENS_CLASSIFICATION
    ADD CONSTRAINT INV_APP_ENS_CLASSIF_TRAC_FK FOREIGN KEY (TRACEABILITY_LEVEL_ID) REFERENCES INV_LKUP_SECURITY_LEVEL (ID);
ALTER TABLE INV_APP_ENS_CLASSIFICATION
    ADD CONSTRAINT INV_APP_ENS_CLASSIF_AVAIL_FK FOREIGN KEY (AVAILABILITY_LEVEL_ID) REFERENCES INV_LKUP_SECURITY_LEVEL (ID);
ALTER TABLE INV_APP_ENS_CLASSIFICATION
    ADD CONSTRAINT INV_APP_ENS_CLASSIF_AUTH_FK FOREIGN KEY (AUTHENTICITY_LEVEL_ID) REFERENCES INV_LKUP_SECURITY_LEVEL (ID);
ALTER TABLE INV_APP_ENS_CLASSIFICATION
    ADD CONSTRAINT INV_APP_ENS_CLASSIF_GRADE_FK FOREIGN KEY (OVERALL_GRADE_LEVEL_ID) REFERENCES INV_LKUP_SECURITY_LEVEL (ID);

ALTER TABLE INV_APP_SECURITY_RISK
    ADD CONSTRAINT INV_APP_SEC_RISK_SEC_FK FOREIGN KEY (APP_SECURITY_ID) REFERENCES INV_APP_SECURITY (ID);
ALTER TABLE INV_APP_SECURITY_RISK
    ADD CONSTRAINT INV_APP_SEC_RISK_LEVEL_FK FOREIGN KEY (LEVEL_ID) REFERENCES INV_LKUP_SECURITY_LEVEL (ID);
ALTER TABLE INV_APP_SECURITY_RISK
    ADD CONSTRAINT INV_APP_SEC_RISK_FIELD_FK FOREIGN KEY (FIELD_ID) REFERENCES INV_FIELD (FIELD_ID);

ALTER TABLE INV_APP_SECURITY_MEASURE
    ADD CONSTRAINT INV_APP_SEC_MEAS_SEC_FK FOREIGN KEY (APP_SECURITY_ID) REFERENCES INV_APP_SECURITY (ID);
ALTER TABLE INV_APP_SECURITY_MEASURE
    ADD CONSTRAINT INV_APP_SEC_MEAS_TYPE_FK FOREIGN KEY (TYPE_ID) REFERENCES INV_SECURITY_MEASURE_TYPE (ID);
ALTER TABLE INV_APP_SECURITY_MEASURE
    ADD CONSTRAINT INV_APP_SEC_MEAS_ENSREQ_FK FOREIGN KEY (ENS_REQUIREMENT_ID) REFERENCES INV_ENS_REQUIREMENT (ID);

ALTER TABLE INV_APP_ACCESSIBILITY
    ADD CONSTRAINT INV_APP_ACCESSIBILITY_APP_FK FOREIGN KEY (APPLICATION_ID) REFERENCES INV_APPLICATION (APP_APPLICATION_ID);
ALTER TABLE INV_APP_ACCESSIBILITY
    ADD CONSTRAINT INV_APP_ACCESS_COMPL_FK FOREIGN KEY (COMPLIANCE_ID) REFERENCES INV_COMPLIANCE_SITUATION (ID);
ALTER TABLE INV_APP_ACCESSIBILITY
    ADD CONSTRAINT INV_APP_ACCESS_PORTAL_CLASS_FK FOREIGN KEY (CLASSIFICATION_SEGMENT_ID) REFERENCES INV_CLASSIFICATION_SEGMENT (ID);
