INSERT INTO INV_LKUP_SECURITY_LEVEL (ID, NAME, NAME_ES)
SELECT INV_LKUP_SECURITY_LEVEL_SEQ.nextval, 'Alt', 'Alto'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_LKUP_SECURITY_LEVEL WHERE NAME = 'Alt');

INSERT INTO INV_LKUP_SECURITY_LEVEL (ID, NAME, NAME_ES)
SELECT INV_LKUP_SECURITY_LEVEL_SEQ.nextval, 'Mitjà', 'Medio'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_LKUP_SECURITY_LEVEL WHERE NAME = 'Mitjà');

INSERT INTO INV_LKUP_SECURITY_LEVEL (ID, NAME, NAME_ES)
SELECT INV_LKUP_SECURITY_LEVEL_SEQ.nextval, 'Baix', 'Bajo'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_LKUP_SECURITY_LEVEL WHERE NAME = 'Baix');

INSERT INTO INV_LKUP_SECURITY_LEVEL (ID, NAME, NAME_ES)
SELECT INV_LKUP_SECURITY_LEVEL_SEQ.nextval, 'NA', 'NA'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_LKUP_SECURITY_LEVEL WHERE NAME = 'NA');

INSERT INTO INV_LKUP_ENS_SUBJECT (ID, NAME, NAME_ES)
SELECT INV_LKUP_ENS_SUBJECT_SEQ.nextval, 'Sí', 'Sí'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_LKUP_ENS_SUBJECT WHERE NAME = 'Sí');

INSERT INTO INV_LKUP_ENS_SUBJECT (ID, NAME, NAME_ES)
SELECT INV_LKUP_ENS_SUBJECT_SEQ.nextval, 'No', 'No'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_LKUP_ENS_SUBJECT WHERE NAME = 'No');

INSERT INTO INV_LKUP_ENS_SUBJECT (ID, NAME, NAME_ES)
SELECT INV_LKUP_ENS_SUBJECT_SEQ.nextval, 'Pendent d''anàlisi', 'Pendiente de análisis'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_LKUP_ENS_SUBJECT WHERE NAME = 'Pendent d''anàlisi');

INSERT INTO INV_COMPLIANCE_SITUATION (ID, NAME, NAME_ES, CREATED_AT, CREATED_BY)
SELECT INV_COMPLIANCE_SITUATION_SEQ.nextval, 'Totalment', 'Totalmente', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_COMPLIANCE_SITUATION WHERE NAME = 'Totalment');

INSERT INTO INV_COMPLIANCE_SITUATION_AUD (AUDIT_ID, COMPLIANCE_SITUATION_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_COMPLIANCE_SITUATION_AUD_SEQ.nextval,
       (SELECT ID FROM INV_COMPLIANCE_SITUATION WHERE NAME = 'Totalment'),
       'Totalment', 'Totalmente', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_COMPLIANCE_SITUATION_AUD WHERE NAME = 'Totalment');

INSERT INTO INV_COMPLIANCE_SITUATION (ID, NAME, NAME_ES, CREATED_AT, CREATED_BY)
SELECT INV_COMPLIANCE_SITUATION_SEQ.nextval, 'Parcialment', 'Parcialmente', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_COMPLIANCE_SITUATION WHERE NAME = 'Parcialment');

INSERT INTO INV_COMPLIANCE_SITUATION_AUD (AUDIT_ID, COMPLIANCE_SITUATION_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_COMPLIANCE_SITUATION_AUD_SEQ.nextval,
       (SELECT ID FROM INV_COMPLIANCE_SITUATION WHERE NAME = 'Parcialment'),
       'Parcialment', 'Parcialmente', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_COMPLIANCE_SITUATION_AUD WHERE NAME = 'Parcialment');

INSERT INTO INV_COMPLIANCE_SITUATION (ID, NAME, NAME_ES, CREATED_AT, CREATED_BY)
SELECT INV_COMPLIANCE_SITUATION_SEQ.nextval, 'No conforme', 'No conforme', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_COMPLIANCE_SITUATION WHERE NAME = 'No conforme');

INSERT INTO INV_COMPLIANCE_SITUATION_AUD (AUDIT_ID, COMPLIANCE_SITUATION_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_COMPLIANCE_SITUATION_AUD_SEQ.nextval,
       (SELECT ID FROM INV_COMPLIANCE_SITUATION WHERE NAME = 'No conforme'),
       'No conforme', 'No conforme', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_COMPLIANCE_SITUATION_AUD WHERE NAME = 'No conforme');

INSERT INTO INV_CLASSIFICATION_SEGMENT (ID, NAME, NAME_ES, CREATED_AT, CREATED_BY)
SELECT INV_CLASSIFICATION_SEGMENT_SEQ.nextval, 'Segment I', 'Segmento I', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_CLASSIFICATION_SEGMENT WHERE NAME = 'Segment I');

INSERT INTO INV_CLASSIFICATION_SEGMENT_AUD (AUDIT_ID, CLASSIFICATION_SEGMENT_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_CLASSIFICATION_SEGMENT_AUD_SEQ.nextval,
       (SELECT ID FROM INV_CLASSIFICATION_SEGMENT WHERE NAME = 'Segment I'),
       'Segment I', 'Segmento I', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_CLASSIFICATION_SEGMENT_AUD WHERE NAME = 'Segment I');

INSERT INTO INV_CLASSIFICATION_SEGMENT (ID, NAME, NAME_ES, CREATED_AT, CREATED_BY)
SELECT INV_CLASSIFICATION_SEGMENT_SEQ.nextval, 'Segment II', 'Segmento II', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_CLASSIFICATION_SEGMENT WHERE NAME = 'Segment II');

INSERT INTO INV_CLASSIFICATION_SEGMENT_AUD (AUDIT_ID, CLASSIFICATION_SEGMENT_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_CLASSIFICATION_SEGMENT_AUD_SEQ.nextval,
       (SELECT ID FROM INV_CLASSIFICATION_SEGMENT WHERE NAME = 'Segment II'),
       'Segment II', 'Segmento II', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_CLASSIFICATION_SEGMENT_AUD WHERE NAME = 'Segment II');

INSERT INTO INV_CLASSIFICATION_SEGMENT (ID, NAME, NAME_ES, CREATED_AT, CREATED_BY)
SELECT INV_CLASSIFICATION_SEGMENT_SEQ.nextval, 'Segment III', 'Segmento III', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_CLASSIFICATION_SEGMENT WHERE NAME = 'Segment III');

INSERT INTO INV_CLASSIFICATION_SEGMENT_AUD (AUDIT_ID, CLASSIFICATION_SEGMENT_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_CLASSIFICATION_SEGMENT_AUD_SEQ.nextval,
       (SELECT ID FROM INV_CLASSIFICATION_SEGMENT WHERE NAME = 'Segment III'),
       'Segment III', 'Segmento III', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_CLASSIFICATION_SEGMENT_AUD WHERE NAME = 'Segment III');

INSERT INTO INV_IDENTITY_PROVIDER (ID, NAME, CREATED_AT, CREATED_BY)
SELECT INV_IDENTITY_PROVIDER_SEQ.nextval, 'Cl@ve', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_IDENTITY_PROVIDER WHERE NAME = 'Cl@ve');

INSERT INTO INV_IDENTITY_PROVIDER_AUD (AUDIT_ID, IDENTITY_PROVIDER_ID, NAME, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_IDENTITY_PROVIDER_AUD_SEQ.nextval,
       (SELECT ID FROM INV_IDENTITY_PROVIDER WHERE NAME = 'Cl@ve'),
       'Cl@ve', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_IDENTITY_PROVIDER_AUD WHERE NAME = 'Cl@ve');

INSERT INTO INV_PERSONAL_DATA_PROCESSING (ID, NAME, NAME_ES, CREATED_AT, CREATED_BY)
SELECT INV_PERS_DATA_PROC_SEQ.nextval, 'Dades de caràcter personal', 'Datos de carácter personal', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_PERSONAL_DATA_PROCESSING WHERE NAME = 'Dades de caràcter personal');

INSERT INTO INV_PERS_DATA_PROC_AUD (AUDIT_ID, PERSONAL_DATA_PROCESSING_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_PERS_DATA_PROC_AUD_SEQ.nextval,
       (SELECT ID FROM INV_PERSONAL_DATA_PROCESSING WHERE NAME = 'Dades de caràcter personal'),
       'Dades de caràcter personal', 'Datos de carácter personal', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_PERS_DATA_PROC_AUD WHERE NAME = 'Dades de caràcter personal');

INSERT INTO INV_WEB_CONTEXT (ID, NAME, NAME_ES, CREATED_AT, CREATED_BY)
SELECT INV_WEB_CONTEXT_SEQ.nextval, 'Portal ciutadà', 'Portal ciudadano', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_WEB_CONTEXT WHERE NAME = 'Portal ciutadà');

INSERT INTO INV_WEB_CONTEXT_AUD (AUDIT_ID, WEB_CONTEXT_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_WEB_CONTEXT_AUD_SEQ.nextval,
       (SELECT ID FROM INV_WEB_CONTEXT WHERE NAME = 'Portal ciutadà'),
       'Portal ciutadà', 'Portal ciudadano', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_WEB_CONTEXT_AUD WHERE NAME = 'Portal ciutadà');

INSERT INTO INV_SECURITY_MEASURE_TYPE (ID, NAME, NAME_ES, CREATED_AT, CREATED_BY)
SELECT INV_SECURITY_MEASURE_TYPE_SEQ.nextval, 'Organitzativa', 'Organizativa', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_SECURITY_MEASURE_TYPE WHERE NAME = 'Organitzativa');

INSERT INTO INV_SECURITY_MEASURE_TYPE_AUD (AUDIT_ID, SECURITY_MEASURE_TYPE_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_SECURITY_MEASURE_TYPE_AUD_SEQ.nextval,
       (SELECT ID FROM INV_SECURITY_MEASURE_TYPE WHERE NAME = 'Organitzativa'),
       'Organitzativa', 'Organizativa', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_SECURITY_MEASURE_TYPE_AUD WHERE NAME = 'Organitzativa');

INSERT INTO INV_ENS_REQUIREMENT (ID, NAME, NAME_ES, CREATED_AT, CREATED_BY)
SELECT INV_ENS_REQUIREMENT_SEQ.nextval, 'Control d''accés', 'Control de acceso', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_ENS_REQUIREMENT WHERE NAME = 'Control d''accés');

INSERT INTO INV_ENS_REQUIREMENT_AUD (AUDIT_ID, ENS_REQUIREMENT_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_ENS_REQUIREMENT_AUD_SEQ.nextval,
       (SELECT ID FROM INV_ENS_REQUIREMENT WHERE NAME = 'Control d''accés'),
       'Control d''accés', 'Control de acceso', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_ENS_REQUIREMENT_AUD WHERE NAME = 'Control d''accés');

-- Locally cached copy of a Soffid role (no local CRUD; see table comment).
INSERT INTO INV_SECURITY_ROLE (ID, ROLE_ID, NAME, SYSTEM, DESCRIPTION, CREATED_AT, CREATED_BY)
SELECT INV_SECURITY_ROLE_SEQ.nextval, 100, 'INVAI_ADMIN_ROLE', 'INVAI', 'Rol administrador de l''aplicació', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_SECURITY_ROLE WHERE ROLE_ID = 100);

INSERT INTO INV_APP_SECURITY (ID, APPLICATION_ID, OBSERVATION, CREATED_AT, CREATED_BY)
SELECT INV_APP_SECURITY_SEQ.nextval,
       (SELECT APP_APPLICATION_ID FROM INV_APPLICATION WHERE CODE = 'APP-001'),
       TO_CLOB('Anàlisi de seguretat inicial de l''aplicació.'),
       SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM INV_APP_SECURITY
    WHERE APPLICATION_ID = (SELECT APP_APPLICATION_ID FROM INV_APPLICATION WHERE CODE = 'APP-001')
);

INSERT INTO INV_APP_SECURITY_AUD (AUDIT_ID, ID, APPLICATION_ID, OBSERVATION, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_APP_SECURITY_AUD_SEQ.nextval, s.ID, s.APPLICATION_ID, s.OBSERVATION, s.CREATED_AT, s.CREATED_BY, 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM INV_APP_SECURITY s
WHERE NOT EXISTS (SELECT 1 FROM INV_APP_SECURITY_AUD sa WHERE sa.ID = s.ID AND sa.AUD_ACTION = 'INSERT');

INSERT INTO INV_APP_ROLE (ID, APP_SECURITY_ID, SECURITY_ROLE_ID, CREATED_AT, CREATED_BY)
SELECT INV_APP_ROLE_SEQ.nextval,
       (SELECT ID FROM INV_APP_SECURITY WHERE APPLICATION_ID = (SELECT APP_APPLICATION_ID FROM INV_APPLICATION WHERE CODE = 'APP-001')),
       (SELECT ID FROM INV_SECURITY_ROLE WHERE ROLE_ID = 100),
       SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM INV_APP_ROLE
    WHERE APP_SECURITY_ID = (SELECT ID FROM INV_APP_SECURITY WHERE APPLICATION_ID = (SELECT APP_APPLICATION_ID FROM INV_APPLICATION WHERE CODE = 'APP-001'))
);

INSERT INTO INV_APP_ROLE_AUD (AUDIT_ID, APP_ROLE_ID, APP_SECURITY_ID, SECURITY_ROLE_ID, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_APP_ROLE_AUD_SEQ.nextval, r.ID, r.APP_SECURITY_ID, r.SECURITY_ROLE_ID, r.CREATED_AT, r.CREATED_BY, 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM INV_APP_ROLE r
WHERE NOT EXISTS (SELECT 1 FROM INV_APP_ROLE_AUD ra WHERE ra.APP_ROLE_ID = r.ID AND ra.AUD_ACTION = 'INSERT');

INSERT INTO INV_APP_WEB_CONTEXT (ID, APP_SECURITY_ID, WEB_CONTEXT_ID, FIELD_ID, OBSERVATION, CREATED_AT, CREATED_BY)
SELECT INV_APP_WEB_CONTEXT_SEQ.nextval,
       (SELECT ID FROM INV_APP_SECURITY WHERE APPLICATION_ID = (SELECT APP_APPLICATION_ID FROM INV_APPLICATION WHERE CODE = 'APP-001')),
       (SELECT ID FROM INV_WEB_CONTEXT WHERE NAME = 'Portal ciutadà'),
       (SELECT FIELD_ID FROM INV_FIELD WHERE NAME = 'Finances'),
       TO_CLOB('Context web públic per a la gestió de factures.'),
       SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM INV_APP_WEB_CONTEXT
    WHERE APP_SECURITY_ID = (SELECT ID FROM INV_APP_SECURITY WHERE APPLICATION_ID = (SELECT APP_APPLICATION_ID FROM INV_APPLICATION WHERE CODE = 'APP-001'))
);

INSERT INTO INV_APP_WEB_CONTEXT_AUD (AUDIT_ID, APP_WEB_CONTEXT_ID, APP_SECURITY_ID, WEB_CONTEXT_ID, FIELD_ID, OBSERVATION, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_APP_WEB_CONTEXT_AUD_SEQ.nextval, w.ID, w.APP_SECURITY_ID, w.WEB_CONTEXT_ID, w.FIELD_ID, w.OBSERVATION, w.CREATED_AT, w.CREATED_BY, 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM INV_APP_WEB_CONTEXT w
WHERE NOT EXISTS (SELECT 1 FROM INV_APP_WEB_CONTEXT_AUD wa WHERE wa.APP_WEB_CONTEXT_ID = w.ID AND wa.AUD_ACTION = 'INSERT');

INSERT INTO INV_APP_ENS_CLASSIFICATION (ID, APP_SECURITY_ID, OVERALL_GRADE_LEVEL_ID, IDENTITY_PROVIDER_ID, ENS_SUBJECT_ID,
                                         PERSONAL_DATA_PROCESSING_ID, APPROVAL_DATE, CONFIDENTIALITY_LEVEL_ID,
                                         INTEGRITY_LEVEL_ID, TRACEABILITY_LEVEL_ID, AVAILABILITY_LEVEL_ID,
                                         AUTHENTICITY_LEVEL_ID, CREATED_AT, CREATED_BY)
SELECT INV_APP_ENS_CLASSIFICATION_SEQ.nextval,
       (SELECT ID FROM INV_APP_SECURITY WHERE APPLICATION_ID = (SELECT APP_APPLICATION_ID FROM INV_APPLICATION WHERE CODE = 'APP-001')),
       (SELECT ID FROM INV_LKUP_SECURITY_LEVEL WHERE NAME = 'Mitjà'),
       (SELECT ID FROM INV_IDENTITY_PROVIDER WHERE NAME = 'Cl@ve'),
       (SELECT ID FROM INV_LKUP_ENS_SUBJECT WHERE NAME = 'Sí'),
       (SELECT ID FROM INV_PERSONAL_DATA_PROCESSING WHERE NAME = 'Dades de caràcter personal'),
       SYSTIMESTAMP,
       (SELECT ID FROM INV_LKUP_SECURITY_LEVEL WHERE NAME = 'Alt'),
       (SELECT ID FROM INV_LKUP_SECURITY_LEVEL WHERE NAME = 'Alt'),
       (SELECT ID FROM INV_LKUP_SECURITY_LEVEL WHERE NAME = 'Mitjà'),
       (SELECT ID FROM INV_LKUP_SECURITY_LEVEL WHERE NAME = 'Mitjà'),
       (SELECT ID FROM INV_LKUP_SECURITY_LEVEL WHERE NAME = 'Baix'),
       SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM INV_APP_ENS_CLASSIFICATION
    WHERE APP_SECURITY_ID = (SELECT ID FROM INV_APP_SECURITY WHERE APPLICATION_ID = (SELECT APP_APPLICATION_ID FROM INV_APPLICATION WHERE CODE = 'APP-001'))
);

INSERT INTO INV_APP_ENS_CLASSIFICATION_AUD (AUDIT_ID, APP_ENS_CLASSIFICATION_ID, APP_SECURITY_ID, OVERALL_GRADE_LEVEL_ID,
                                             IDENTITY_PROVIDER_ID, ENS_SUBJECT_ID, PERSONAL_DATA_PROCESSING_ID, APPROVAL_DATE,
                                             CONFIDENTIALITY_LEVEL_ID, INTEGRITY_LEVEL_ID, TRACEABILITY_LEVEL_ID,
                                             AVAILABILITY_LEVEL_ID, AUTHENTICITY_LEVEL_ID, CREATED_AT, CREATED_BY,
                                             AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_APP_ENS_CLASSIFICATION_AUD_SEQ.nextval, e.ID, e.APP_SECURITY_ID, e.OVERALL_GRADE_LEVEL_ID,
       e.IDENTITY_PROVIDER_ID, e.ENS_SUBJECT_ID, e.PERSONAL_DATA_PROCESSING_ID, e.APPROVAL_DATE,
       e.CONFIDENTIALITY_LEVEL_ID, e.INTEGRITY_LEVEL_ID, e.TRACEABILITY_LEVEL_ID,
       e.AVAILABILITY_LEVEL_ID, e.AUTHENTICITY_LEVEL_ID, e.CREATED_AT, e.CREATED_BY,
       'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM INV_APP_ENS_CLASSIFICATION e
WHERE NOT EXISTS (SELECT 1 FROM INV_APP_ENS_CLASSIFICATION_AUD ea WHERE ea.APP_ENS_CLASSIFICATION_ID = e.ID AND ea.AUD_ACTION = 'INSERT');

INSERT INTO INV_APP_SECURITY_RISK (ID, APP_SECURITY_ID, LEVEL_ID, DESCRIPTION, FIELD_ID, CREATED_AT, CREATED_BY)
SELECT INV_APP_SECURITY_RISK_SEQ.nextval,
       (SELECT ID FROM INV_APP_SECURITY WHERE APPLICATION_ID = (SELECT APP_APPLICATION_ID FROM INV_APPLICATION WHERE CODE = 'APP-001')),
       (SELECT ID FROM INV_LKUP_SECURITY_LEVEL WHERE NAME = 'Mitjà'),
       TO_CLOB('Risc d''accés no autoritzat a dades sensibles.'),
       (SELECT FIELD_ID FROM INV_FIELD WHERE NAME = 'Finances'),
       SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM INV_APP_SECURITY_RISK
    WHERE APP_SECURITY_ID = (SELECT ID FROM INV_APP_SECURITY WHERE APPLICATION_ID = (SELECT APP_APPLICATION_ID FROM INV_APPLICATION WHERE CODE = 'APP-001'))
);

INSERT INTO INV_APP_SECURITY_RISK_AUD (AUDIT_ID, APP_SECURITY_RISK_ID, APP_SECURITY_ID, LEVEL_ID, DESCRIPTION, FIELD_ID, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_APP_SECURITY_RISK_AUD_SEQ.nextval, sr.ID, sr.APP_SECURITY_ID, sr.LEVEL_ID, sr.DESCRIPTION, sr.FIELD_ID, sr.CREATED_AT, sr.CREATED_BY, 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM INV_APP_SECURITY_RISK sr
WHERE NOT EXISTS (SELECT 1 FROM INV_APP_SECURITY_RISK_AUD sra WHERE sra.APP_SECURITY_RISK_ID = sr.ID AND sra.AUD_ACTION = 'INSERT');

INSERT INTO INV_APP_SECURITY_MEASURE (ID, APP_SECURITY_ID, TYPE_ID, ENS_REQUIREMENT_ID, DESCRIPTION, CREATED_AT, CREATED_BY)
SELECT INV_APP_SECURITY_MEASURE_SEQ.nextval,
       (SELECT ID FROM INV_APP_SECURITY WHERE APPLICATION_ID = (SELECT APP_APPLICATION_ID FROM INV_APPLICATION WHERE CODE = 'APP-001')),
       (SELECT ID FROM INV_SECURITY_MEASURE_TYPE WHERE NAME = 'Organitzativa'),
       (SELECT ID FROM INV_ENS_REQUIREMENT WHERE NAME = 'Control d''accés'),
       TO_CLOB('Política de control d''accés basada en rols (RBAC).'),
       SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM INV_APP_SECURITY_MEASURE
    WHERE APP_SECURITY_ID = (SELECT ID FROM INV_APP_SECURITY WHERE APPLICATION_ID = (SELECT APP_APPLICATION_ID FROM INV_APPLICATION WHERE CODE = 'APP-001'))
);

INSERT INTO INV_APP_SECURITY_MEASURE_AUD (AUDIT_ID, APP_SECURITY_MEASURE_ID, APP_SECURITY_ID, TYPE_ID, ENS_REQUIREMENT_ID, DESCRIPTION, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_APP_SECURITY_MEASURE_AUD_SEQ.nextval, sm.ID, sm.APP_SECURITY_ID, sm.TYPE_ID, sm.ENS_REQUIREMENT_ID, sm.DESCRIPTION, sm.CREATED_AT, sm.CREATED_BY, 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM INV_APP_SECURITY_MEASURE sm
WHERE NOT EXISTS (SELECT 1 FROM INV_APP_SECURITY_MEASURE_AUD sma WHERE sma.APP_SECURITY_MEASURE_ID = sm.ID AND sma.AUD_ACTION = 'INSERT');

INSERT INTO INV_APP_ACCESSIBILITY (ID, APPLICATION_ID, CLASSIFICATION_SEGMENT_ID, COMPLIANCE_ID, PUBLIC_URL,
                                    MOBILE_APPLICATION, MOBILE_APPLICATION_NAME, NON_ACCESSIBLE_CONTENT, OBSERVATIONS,
                                    EXPIRE_DATE, CREATED_AT, CREATED_BY)
SELECT INV_APP_ACCESSIBILITY_SEQ.nextval,
       (SELECT APP_APPLICATION_ID FROM INV_APPLICATION WHERE CODE = 'APP-001'),
       (SELECT ID FROM INV_CLASSIFICATION_SEGMENT WHERE NAME = 'Segment I'),
       (SELECT ID FROM INV_COMPLIANCE_SITUATION WHERE NAME = 'Totalment'),
       'https://factures.caib.es',
       1,
       'APP INVAI Android',
       TO_CLOB('Alguns documents PDF històrics no disposen de text alternatiu.'),
       TO_CLOB('Pendent de revisió anual d''accessibilitat.'),
       ADD_MONTHS(SYSTIMESTAMP, 12),
       SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM INV_APP_ACCESSIBILITY
    WHERE APPLICATION_ID = (SELECT APP_APPLICATION_ID FROM INV_APPLICATION WHERE CODE = 'APP-001')
);

INSERT INTO INV_APP_ACCESSIBILITY_AUD (AUDIT_ID, APP_ACCESSIBILITY_ID, APPLICATION_ID, CLASSIFICATION_SEGMENT_ID, COMPLIANCE_ID,
                                        MOBILE_APPLICATION, MOBILE_APPLICATION_NAME, PUBLIC_URL, NON_ACCESSIBLE_CONTENT,
                                        OBSERVATIONS, EXPIRE_DATE, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_APP_ACCESSIBILITY_AUD_SEQ.nextval, ac.ID, ac.APPLICATION_ID, ac.CLASSIFICATION_SEGMENT_ID, ac.COMPLIANCE_ID,
       ac.MOBILE_APPLICATION, ac.MOBILE_APPLICATION_NAME, ac.PUBLIC_URL, ac.NON_ACCESSIBLE_CONTENT,
       ac.OBSERVATIONS, ac.EXPIRE_DATE, ac.CREATED_AT, ac.CREATED_BY, 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM INV_APP_ACCESSIBILITY ac
WHERE NOT EXISTS (SELECT 1 FROM INV_APP_ACCESSIBILITY_AUD aca WHERE aca.APP_ACCESSIBILITY_ID = ac.ID AND aca.AUD_ACTION = 'INSERT');

INSERT INTO INV_APP_SECURITY (ID, APPLICATION_ID, CREATED_AT, CREATED_BY)
SELECT INV_APP_SECURITY_SEQ.nextval, a.APP_APPLICATION_ID, SYSTIMESTAMP, 'ADMIN'
FROM INV_APPLICATION a
WHERE NOT EXISTS (SELECT 1 FROM INV_APP_SECURITY s WHERE s.APPLICATION_ID = a.APP_APPLICATION_ID);

INSERT INTO INV_APP_SECURITY_AUD (AUDIT_ID, ID, APPLICATION_ID, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_APP_SECURITY_AUD_SEQ.nextval, s.ID, s.APPLICATION_ID, s.CREATED_AT, s.CREATED_BY, 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM INV_APP_SECURITY s
WHERE NOT EXISTS (SELECT 1 FROM INV_APP_SECURITY_AUD sa WHERE sa.ID = s.ID AND sa.AUD_ACTION = 'INSERT');

INSERT INTO INV_APP_ACCESSIBILITY (ID, APPLICATION_ID, CREATED_AT, CREATED_BY)
SELECT INV_APP_ACCESSIBILITY_SEQ.nextval, a.APP_APPLICATION_ID, SYSTIMESTAMP, 'ADMIN'
FROM INV_APPLICATION a
WHERE NOT EXISTS (SELECT 1 FROM INV_APP_ACCESSIBILITY ac WHERE ac.APPLICATION_ID = a.APP_APPLICATION_ID);

INSERT INTO INV_APP_ACCESSIBILITY_AUD (AUDIT_ID, APP_ACCESSIBILITY_ID, APPLICATION_ID, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_APP_ACCESSIBILITY_AUD_SEQ.nextval, ac.ID, ac.APPLICATION_ID, ac.CREATED_AT, ac.CREATED_BY, 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM INV_APP_ACCESSIBILITY ac
WHERE NOT EXISTS (SELECT 1 FROM INV_APP_ACCESSIBILITY_AUD aca WHERE aca.APP_ACCESSIBILITY_ID = ac.ID AND aca.AUD_ACTION = 'INSERT');

UPDATE INV_APPLICATION a
   SET ADM_UNIT_CODE = (SELECT CODE FROM INV_ADM_UNIT u WHERE u.ADM_UNIT_ID = a.ADM_UNIT_ID)
 WHERE a.ADM_UNIT_ID IS NOT NULL;

UPDATE INV_APPLICATION_AUD a
   SET ADM_UNIT_CODE = (SELECT CODE FROM INV_ADM_UNIT u WHERE u.ADM_UNIT_ID = a.ADM_UNIT_ID)
 WHERE a.ADM_UNIT_ID IS NOT NULL;

COMMIT;
