CREATE UNIQUE INDEX INV_PERSON_EMAIL_ACTIVE_UK_I ON INV_PERSON (EMAIL, CASE
                                                                           WHEN DELETED_AT IS NULL
                                                                               THEN 0 END) TABLESPACE INVAI_INDEX;
DROP INDEX INV_APPLICATION_ADM_UNIT_ID_I;
ALTER TABLE INV_APPLICATION
    DROP COLUMN ADM_UNIT_ID CASCADE CONSTRAINTS;
ALTER TABLE INV_APPLICATION_AUD
    DROP COLUMN ADM_UNIT_ID;

CREATE INDEX INV_APPLICATION_ADM_UNIT_CODE_I ON INV_APPLICATION (ADM_UNIT_CODE) TABLESPACE INVAI_INDEX;

DROP TABLE INV_ADM_UNIT_AUD CASCADE CONSTRAINTS;
DROP TABLE INV_ADM_UNIT CASCADE CONSTRAINTS;
DROP SEQUENCE INV_ADM_UNIT_SEQ;
DROP SEQUENCE INV_ADM_UNIT_AUD_SEQ;
