ALTER TABLE INV_APP_WEB_CONTEXT ADD (URL VARCHAR2(255 CHAR));
ALTER TABLE INV_APP_WEB_CONTEXT_AUD ADD (URL VARCHAR2(255 CHAR));

ALTER TABLE INV_COMPANY ADD (NIF VARCHAR2(20 CHAR));
ALTER TABLE INV_COMPANY_AUD ADD (NIF VARCHAR2(20 CHAR));

ALTER TABLE INV_APP_RESPONSIBLE ADD (DIR3_VALIDATION_ID NUMBER(19));
ALTER TABLE INV_APP_RESPONSIBLE_AUD ADD (DIR3_VALIDATION_ID NUMBER(19));

ALTER TABLE INV_APP_AUTHORIZED ADD (DIR3_VALIDATION_ID NUMBER(19));
ALTER TABLE INV_APP_AUTHORIZED_AUD ADD (DIR3_VALIDATION_ID NUMBER(19));

ALTER TABLE INV_APPLICATION ADD (DIR3_MISMATCH NUMBER(1) DEFAULT 0 NOT NULL);
ALTER TABLE INV_APPLICATION_AUD ADD (DIR3_MISMATCH NUMBER(1));

ALTER TABLE INV_PERSON ADD (USER_NAME VARCHAR2(64 CHAR));
ALTER TABLE INV_PERSON_AUD ADD (USER_NAME VARCHAR2(64 CHAR));

ALTER TABLE INV_APP_WEB_CONTEXT ADD (APP_DEVELOPMENT_ID NUMBER(19));
ALTER TABLE INV_APP_WEB_CONTEXT_AUD ADD (APP_DEVELOPMENT_ID NUMBER(19));

ALTER TABLE INV_APP_WEB_CONTEXT ADD (VALIDATED NUMBER(1) DEFAULT 0 NOT NULL);
ALTER TABLE INV_APP_WEB_CONTEXT_AUD ADD (VALIDATED NUMBER(1));

ALTER TABLE INV_APP_WEB_CONTEXT ADD (VALIDATED_AT TIMESTAMP(6));
ALTER TABLE INV_APP_WEB_CONTEXT_AUD ADD (VALIDATED_AT TIMESTAMP(6));

ALTER TABLE INV_APP_WEB_CONTEXT ADD (VALIDATED_BY VARCHAR2(64 CHAR));
ALTER TABLE INV_APP_WEB_CONTEXT_AUD ADD (VALIDATED_BY VARCHAR2(64 CHAR));

ALTER TABLE INV_APP_WEB_CONTEXT ADD (VALIDATED_REASON CLOB);
ALTER TABLE INV_APP_WEB_CONTEXT_AUD ADD (VALIDATED_REASON CLOB);

-- Retrofits an audit trail onto INV_APP_AUTHORIZED_TYPE_LINK, previously hard-deleted/no-audit since 1.0.3
ALTER TABLE INV_APP_AUTHORIZED_TYPE_LINK ADD (CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL);
ALTER TABLE INV_APP_AUTHORIZED_TYPE_LINK ADD (CREATED_BY VARCHAR2(64 CHAR) DEFAULT 'MIGRATION' NOT NULL);
ALTER TABLE INV_APP_AUTHORIZED_TYPE_LINK ADD (UPDATED_AT TIMESTAMP(6));
ALTER TABLE INV_APP_AUTHORIZED_TYPE_LINK ADD (UPDATED_BY VARCHAR2(64 CHAR));
ALTER TABLE INV_APP_AUTHORIZED_TYPE_LINK ADD (DELETED_AT TIMESTAMP(6));
ALTER TABLE INV_APP_AUTHORIZED_TYPE_LINK ADD (DELETED_BY VARCHAR2(64 CHAR));
