CREATE UNIQUE INDEX INV_LKUP_DIR3_STATUS_PK_I ON INV_LKUP_DIR3_STATUS (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_DIR3_VALIDATION_PK_I ON INV_DIR3_VALIDATION (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_DIR3_VALIDATION_AUD_PK_I ON INV_DIR3_VALIDATION_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_DATA_PK_I ON INV_APP_DATA (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_DATA_AUD_PK_I ON INV_APP_DATA_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_DATA_APP_I ON INV_APP_DATA (APPLICATION_ID) TABLESPACE INVAI_INDEX;

CREATE UNIQUE INDEX INV_EXTERNAL_SYSTEM_PK_I ON INV_EXTERNAL_SYSTEM (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_EXTERNAL_SYSTEM_AUD_PK_I ON INV_EXTERNAL_SYSTEM_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_EXTERNAL_SYSTEM_COMP_I ON INV_EXTERNAL_SYSTEM (COMPANY_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_EXTERNAL_SYSTEM_NAME_UK_I ON INV_EXTERNAL_SYSTEM (CASE WHEN DELETED_AT IS NULL THEN NAME ELSE NULL END) TABLESPACE INVAI_INDEX;

CREATE UNIQUE INDEX INV_APP_INTEGRATION_PK_I ON INV_APP_INTEGRATION (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_INTEGRATION_AUD_PK_I ON INV_APP_INTEGRATION_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_INTEGRATION_APP_I ON INV_APP_INTEGRATION (APPLICATION_ID) TABLESPACE INVAI_INDEX;

CREATE UNIQUE INDEX INV_APP_INTEGR_CONN_PK_I ON INV_APP_INTEGRATION_CONN (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_INTEGR_CONN_AUD_PK_I ON INV_APP_INTEGRATION_CONN_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_INTEGR_CONN_PARENT_I ON INV_APP_INTEGRATION_CONN (APP_INTEGRATION_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_INTEGR_CONN_APP_I ON INV_APP_INTEGRATION_CONN (APPLICATION_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_INTEGR_CONN_EXTSYS_I ON INV_APP_INTEGRATION_CONN (EXTERNAL_SYSTEM_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_INTEGR_CONN_TECH_I ON INV_APP_INTEGRATION_CONN (TECHNOLOGY_ID) TABLESPACE INVAI_INDEX;

CREATE UNIQUE INDEX INV_APP_INTEGR_REQ_RL_PK_I ON INV_APP_INTEGR_REQ_RL (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_INTEGR_REQ_RL_AUD_PK_I ON INV_APP_INTEGR_REQ_RL_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_INTEGR_REQ_RL_CONN_I ON INV_APP_INTEGR_REQ_RL (APP_INTEGRATION_CONN_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_AUTH_TYPE_LINK_AUD_PK_I ON INV_APP_AUTHORIZED_TYPE_LINK_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
