ALTER TABLE INV_LKUP_DIR3_STATUS
    ADD CONSTRAINT INV_LKUP_DIR3_STATUS_PK PRIMARY KEY (ID) USING INDEX INV_LKUP_DIR3_STATUS_PK_I;

ALTER TABLE INV_DIR3_VALIDATION
    ADD CONSTRAINT INV_DIR3_VALIDATION_PK PRIMARY KEY (ID) USING INDEX INV_DIR3_VALIDATION_PK_I;
ALTER TABLE INV_DIR3_VALIDATION
    ADD CONSTRAINT INV_DIR3_VALIDATION_STATUS_FK FOREIGN KEY (DIR3_STATUS_ID) REFERENCES INV_LKUP_DIR3_STATUS (ID);

ALTER TABLE INV_DIR3_VALIDATION_AUD
    ADD CONSTRAINT INV_DIR3_VALIDATION_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_DIR3_VALIDATION_AUD_PK_I;

ALTER TABLE INV_APP_RESPONSIBLE
    ADD CONSTRAINT INV_APP_RESPONSIBLE_DIR3_FK FOREIGN KEY (DIR3_VALIDATION_ID) REFERENCES INV_DIR3_VALIDATION (ID);
COMMENT ON COLUMN INV_APP_RESPONSIBLE.DIR3_VALIDATION_ID IS 'DIR3 validation state of this assignment (INV_DIR3_VALIDATION)';
COMMENT ON COLUMN INV_APP_RESPONSIBLE_AUD.DIR3_VALIDATION_ID IS 'Identifier of the linked DIR3 validation record at the time of the change';

ALTER TABLE INV_APP_AUTHORIZED
    ADD CONSTRAINT INV_APP_AUTHORIZED_DIR3_FK FOREIGN KEY (DIR3_VALIDATION_ID) REFERENCES INV_DIR3_VALIDATION (ID);
COMMENT ON COLUMN INV_APP_AUTHORIZED.DIR3_VALIDATION_ID IS 'DIR3 validation state of this assignment (INV_DIR3_VALIDATION)';
COMMENT ON COLUMN INV_APP_AUTHORIZED_AUD.DIR3_VALIDATION_ID IS 'Identifier of the linked DIR3 validation record at the time of the change';

COMMENT ON COLUMN INV_APPLICATION.DIR3_MISMATCH IS 'Whether at least one active, Personal CAIB responsible/authorized assignment''s DIR3 currently mismatches ADM_UNIT_CODE, as of the last bulk DIR3 audit run (MANUAL assignments never count)';
COMMENT ON COLUMN INV_APPLICATION_AUD.DIR3_MISMATCH IS 'Snapshot of DIR3_MISMATCH at the time of the audited change';

COMMENT ON COLUMN INV_PERSON.USER_NAME IS 'Soffid username (codigo de usuario, e.g. "u8443") of this CAIB staff member; null for external persons or legacy records predating this column';
COMMENT ON COLUMN INV_PERSON_AUD.USER_NAME IS 'Snapshot of USER_NAME at the time of the audited change';

ALTER TABLE INV_APP_WEB_CONTEXT
    ADD CONSTRAINT INV_APP_WEB_CONTEXT_DEV_FK FOREIGN KEY (APP_DEVELOPMENT_ID) REFERENCES INV_APP_DEVELOPMENT (ID);

COMMENT ON COLUMN INV_APP_WEB_CONTEXT.APP_DEVELOPMENT_ID IS 'Development anchor ("Desenvolupament" tab) this web context is assigned to - the only anchor CRUD is exposed from';
COMMENT ON COLUMN INV_APP_WEB_CONTEXT_AUD.APP_DEVELOPMENT_ID IS 'Snapshot of APP_DEVELOPMENT_ID at the time of the audited change';

COMMENT ON COLUMN INV_APP_WEB_CONTEXT.VALIDATED IS 'Whether Security has validated this web context. One-way: never reset back to 0';
COMMENT ON COLUMN INV_APP_WEB_CONTEXT_AUD.VALIDATED IS 'Snapshot of VALIDATED at the time of the audited change';

COMMENT ON COLUMN INV_APP_WEB_CONTEXT.VALIDATED_AT IS 'Timestamp at which Security validated this web context, or null if not yet validated';
COMMENT ON COLUMN INV_APP_WEB_CONTEXT_AUD.VALIDATED_AT IS 'Snapshot of VALIDATED_AT at the time of the audited change';

COMMENT ON COLUMN INV_APP_WEB_CONTEXT.VALIDATED_BY IS 'User who validated this web context, or null if not yet validated';
COMMENT ON COLUMN INV_APP_WEB_CONTEXT_AUD.VALIDATED_BY IS 'Snapshot of VALIDATED_BY at the time of the audited change';

COMMENT ON COLUMN INV_APP_WEB_CONTEXT.VALIDATED_REASON IS 'Free-text justification given by Security at validation time, or null if not yet validated';
COMMENT ON COLUMN INV_APP_WEB_CONTEXT_AUD.VALIDATED_REASON IS 'Snapshot of VALIDATED_REASON at the time of the audited change';

ALTER TABLE INV_APP_DATA
    ADD CONSTRAINT INV_APP_DATA_PK PRIMARY KEY (ID) USING INDEX INV_APP_DATA_PK_I;
ALTER TABLE INV_APP_DATA
    ADD CONSTRAINT INV_APP_DATA_APP_FK FOREIGN KEY (APPLICATION_ID) REFERENCES INV_APPLICATION (APP_APPLICATION_ID);

ALTER TABLE INV_APP_DATA_AUD
    ADD CONSTRAINT INV_APP_DATA_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_DATA_AUD_PK_I;

ALTER TABLE INV_EXTERNAL_SYSTEM
    ADD CONSTRAINT INV_EXTERNAL_SYSTEM_PK PRIMARY KEY (ID) USING INDEX INV_EXTERNAL_SYSTEM_PK_I;
ALTER TABLE INV_EXTERNAL_SYSTEM
    ADD CONSTRAINT INV_EXTERNAL_SYSTEM_COMP_FK FOREIGN KEY (COMPANY_ID) REFERENCES INV_COMPANY (ID);
ALTER TABLE INV_EXTERNAL_SYSTEM_AUD
    ADD CONSTRAINT INV_EXTERNAL_SYSTEM_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_EXTERNAL_SYSTEM_AUD_PK_I;

ALTER TABLE INV_APP_INTEGRATION
    ADD CONSTRAINT INV_APP_INTEGRATION_PK PRIMARY KEY (ID) USING INDEX INV_APP_INTEGRATION_PK_I;
ALTER TABLE INV_APP_INTEGRATION
    ADD CONSTRAINT INV_APP_INTEGRATION_APP_FK FOREIGN KEY (APPLICATION_ID) REFERENCES INV_APPLICATION (APP_APPLICATION_ID);
ALTER TABLE INV_APP_INTEGRATION_AUD
    ADD CONSTRAINT INV_APP_INTEGRATION_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_INTEGRATION_AUD_PK_I;

ALTER TABLE INV_APP_INTEGRATION_CONN
    ADD CONSTRAINT INV_APP_INTEGR_CONN_PK PRIMARY KEY (ID) USING INDEX INV_APP_INTEGR_CONN_PK_I;
ALTER TABLE INV_APP_INTEGRATION_CONN
    ADD CONSTRAINT INV_APP_INTEGR_CONN_PARENT_FK FOREIGN KEY (APP_INTEGRATION_ID) REFERENCES INV_APP_INTEGRATION (ID);
ALTER TABLE INV_APP_INTEGRATION_CONN
    ADD CONSTRAINT INV_APP_INTEGR_CONN_APP_FK FOREIGN KEY (APPLICATION_ID) REFERENCES INV_APPLICATION (APP_APPLICATION_ID);
ALTER TABLE INV_APP_INTEGRATION_CONN
    ADD CONSTRAINT INV_APP_INTEGR_CONN_EXTSYS_FK FOREIGN KEY (EXTERNAL_SYSTEM_ID) REFERENCES INV_EXTERNAL_SYSTEM (ID);
ALTER TABLE INV_APP_INTEGRATION_CONN
    ADD CONSTRAINT INV_APP_INTEGR_CONN_TECH_FK FOREIGN KEY (TECHNOLOGY_ID) REFERENCES INV_TECHNOLOGY (ID);
ALTER TABLE INV_APP_INTEGRATION_CONN_AUD
    ADD CONSTRAINT INV_APP_INTEGR_CONN_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_INTEGR_CONN_AUD_PK_I;

ALTER TABLE INV_APP_INTEGR_REQ_RL
    ADD CONSTRAINT INV_APP_INTEGR_REQ_RL_PK PRIMARY KEY (ID) USING INDEX INV_APP_INTEGR_REQ_RL_PK_I;
ALTER TABLE INV_APP_INTEGR_REQ_RL
    ADD CONSTRAINT INV_APP_INTEGR_REQ_RL_CONN_FK FOREIGN KEY (APP_INTEGRATION_CONN_ID) REFERENCES INV_APP_INTEGRATION_CONN (ID);
ALTER TABLE INV_APP_INTEGR_REQ_RL_AUD
    ADD CONSTRAINT INV_APP_INTEGR_REQ_RL_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_INTEGR_REQ_RL_AUD_PK_I;
ALTER TABLE INV_APP_AUTHORIZED_TYPE_LINK_AUD
    ADD CONSTRAINT INV_APP_AUTH_TYPE_LINK_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_AUTH_TYPE_LINK_AUD_PK_I;
