
ALTER TABLE INV_APP_RESPONSIBLE MODIFY (DIR3_VALIDATION_ID NUMBER(19) NOT NULL);
ALTER TABLE INV_APP_AUTHORIZED MODIFY (DIR3_VALIDATION_ID NUMBER(19) NOT NULL);
ALTER TABLE INV_APP_WEB_CONTEXT MODIFY (APP_DEVELOPMENT_ID NUMBER(19) NOT NULL);
