-- 1. Eliminar las Secuencias
DROP SEQUENCE INV_ENVIRONMENT_SEQ;
DROP SEQUENCE INV_LKUP_SERVER_TYPE_SEQ;
DROP SEQUENCE INV_SERVER_SEQ;
DROP SEQUENCE INV_SYSTEM_SEQ;
DROP SEQUENCE INV_DATABASE_SEQ;
DROP SEQUENCE INV_APP_INF_SYS_DB_SEQ;
DROP SEQUENCE INV_APP_SYSTEM_SEQ;
DROP SEQUENCE INV_APP_DATABASE_SEQ;
DROP SEQUENCE INV_LKUP_MODALITY_SEQ;
DROP SEQUENCE INV_LKUP_STANDARD_ADAPTION_SEQ;
DROP SEQUENCE INV_APP_DEVELOPMENT_SEQ;
DROP SEQUENCE INV_APP_PROVIDER_SEQ;
DROP SEQUENCE INV_APP_TECHNOLOGY_SEQ;
DROP SEQUENCE INV_DATABASE_VENDOR_SEQ;
DROP SEQUENCE INV_ROLE_SEQ;
DROP SEQUENCE INV_LAYER_SEQ;
DROP SEQUENCE INV_TECHNOLOGY_SEQ;

DROP SEQUENCE INV_ENVIRONMENT_AUD_SEQ;
DROP SEQUENCE INV_SERVER_AUD_SEQ;
DROP SEQUENCE INV_SYSTEM_AUD_SEQ;
DROP SEQUENCE INV_DATABASE_AUD_SEQ;
DROP SEQUENCE INV_APP_INF_SYS_DB_AUD_SEQ;
DROP SEQUENCE INV_APP_SYSTEM_AUD_SEQ;
DROP SEQUENCE INV_APP_DATABASE_AUD_SEQ;
DROP SEQUENCE INV_APP_DEVELOPMENT_AUD_SEQ;
DROP SEQUENCE INV_APP_PROVIDER_AUD_SEQ;
DROP SEQUENCE INV_APP_TECHNOLOGY_AUD_SEQ;
DROP SEQUENCE INV_DATABASE_VENDOR_AUD_SEQ;
DROP SEQUENCE INV_ROLE_AUD_SEQ;
DROP SEQUENCE INV_LAYER_AUD_SEQ;
DROP SEQUENCE INV_TECHNOLOGY_AUD_SEQ;

-- 2. Eliminar las Tablas
-- Usamos CASCADE CONSTRAINTS para borrar automáticamente
-- los índices y constraints asociados sin importar el orden.
DROP TABLE INV_APP_TECHNOLOGY_AUD            CASCADE CONSTRAINTS;
DROP TABLE INV_APP_TECHNOLOGY                CASCADE CONSTRAINTS;
DROP TABLE INV_APP_PROVIDER_AUD              CASCADE CONSTRAINTS;
DROP TABLE INV_APP_PROVIDER                  CASCADE CONSTRAINTS;
DROP TABLE INV_TECHNOLOGY_AUD                CASCADE CONSTRAINTS;
DROP TABLE INV_TECHNOLOGY                    CASCADE CONSTRAINTS;
DROP TABLE INV_LAYER_AUD                     CASCADE CONSTRAINTS;
DROP TABLE INV_LAYER                         CASCADE CONSTRAINTS;
DROP TABLE INV_ROLE_AUD                      CASCADE CONSTRAINTS;
DROP TABLE INV_ROLE                          CASCADE CONSTRAINTS;
DROP TABLE INV_APP_DEVELOPMENT_AUD           CASCADE CONSTRAINTS;
DROP TABLE INV_APP_DEVELOPMENT               CASCADE CONSTRAINTS;
DROP TABLE INV_LKUP_STANDARD_ADAPTION        CASCADE CONSTRAINTS;
DROP TABLE INV_LKUP_MODALITY                 CASCADE CONSTRAINTS;
DROP TABLE INV_APP_DATABASE_AUD              CASCADE CONSTRAINTS;
DROP TABLE INV_APP_DATABASE                  CASCADE CONSTRAINTS;
DROP TABLE INV_APP_SYSTEM_AUD                CASCADE CONSTRAINTS;
DROP TABLE INV_APP_SYSTEM                    CASCADE CONSTRAINTS;
DROP TABLE INV_APP_INFORMATION_SYSTEM_DB_AUD CASCADE CONSTRAINTS;
DROP TABLE INV_APP_INFORMATION_SYSTEM_DB     CASCADE CONSTRAINTS;
DROP TABLE INV_DATABASE_AUD                  CASCADE CONSTRAINTS;
DROP TABLE INV_DATABASE                      CASCADE CONSTRAINTS;
DROP TABLE INV_DATABASE_VENDOR_AUD           CASCADE CONSTRAINTS;
DROP TABLE INV_DATABASE_VENDOR               CASCADE CONSTRAINTS;
DROP TABLE INV_SYSTEM_AUD                    CASCADE CONSTRAINTS;
DROP TABLE INV_SYSTEM                        CASCADE CONSTRAINTS;
DROP TABLE INV_SERVER_AUD                    CASCADE CONSTRAINTS;
DROP TABLE INV_SERVER                        CASCADE CONSTRAINTS;
DROP TABLE INV_LKUP_SERVER_TYPE              CASCADE CONSTRAINTS;
DROP TABLE INV_ENVIRONMENT_AUD               CASCADE CONSTRAINTS;
DROP TABLE INV_ENVIRONMENT                   CASCADE CONSTRAINTS;
