CREATE UNIQUE INDEX INV_ENV_PK_I ON INV_ENVIRONMENT (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_LKUP_SERVER_TYPE_PK_I ON INV_LKUP_SERVER_TYPE (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_LKUP_SERVER_TYPE_CODE_UK_I ON INV_LKUP_SERVER_TYPE (CODE) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_SERVER_PK_I ON INV_SERVER (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_SERVER_UK_I ON INV_SERVER (ID, NAME) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_SYSTEM_PK_I ON INV_SYSTEM (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_DATABASE_VENDOR_PK_I ON INV_DATABASE_VENDOR (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_DATABASE_PK_I ON INV_DATABASE (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_INF_SYS_DB_PK_I ON INV_APP_INFORMATION_SYSTEM_DB (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_SYSTEM_PK_I ON INV_APP_SYSTEM (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_DATABASE_PK_I ON INV_APP_DATABASE (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_LKUP_MODALITY_PK_I ON INV_LKUP_MODALITY (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_STD_ADAPT_LKUP_PK_I ON INV_LKUP_STANDARD_ADAPTION (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_DEV_PK_I ON INV_APP_DEVELOPMENT (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_PROVIDER_PK_I ON INV_APP_PROVIDER (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_TECH_PK_I ON INV_APP_TECHNOLOGY (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_ROLE_PK_I ON INV_ROLE (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_LAYER_PK_I ON INV_LAYER (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_TECHNOLOGY_PK_I ON INV_TECHNOLOGY (ID) TABLESPACE INVAI_INDEX;

CREATE UNIQUE INDEX INV_ENV_AUD_PK_I ON INV_ENVIRONMENT_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_SERVER_AUD_PK_I ON INV_SERVER_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_SYSTEM_AUD_PK_I ON INV_SYSTEM_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_DB_VENDOR_AUD_PK_I ON INV_DATABASE_VENDOR_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_DATABASE_AUD_PK_I ON INV_DATABASE_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_INF_SYS_DB_AUD_PK_I ON INV_APP_INFORMATION_SYSTEM_DB_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_SYSTEM_AUD_PK_I ON INV_APP_SYSTEM_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_DATABASE_AUD_PK_I ON INV_APP_DATABASE_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_DEV_AUD_PK_I ON INV_APP_DEVELOPMENT_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_PROVIDER_AUD_PK_I ON INV_APP_PROVIDER_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_TECH_AUD_PK_I ON INV_APP_TECHNOLOGY_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_ROLE_AUD_PK_I ON INV_ROLE_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_LAYER_AUD_PK_I ON INV_LAYER_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_TECHNOLOGY_AUD_PK_I ON INV_TECHNOLOGY_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;

CREATE INDEX INV_SERVER_ENV_I ON INV_SERVER (ENVIRONMENT_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_SERVER_TYPE_I ON INV_SERVER (SERVER_TYPE_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_SYSTEM_SERVER_I ON INV_SYSTEM (SERVER_ID) TABLESPACE INVAI_INDEX;

CREATE INDEX INV_DATABASE_SERVER_I ON INV_DATABASE (SERVER_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_DATABASE_VENDOR_I ON INV_DATABASE (DATABASE_TYPE) TABLESPACE INVAI_INDEX;

CREATE INDEX INV_APP_INF_SYS_DB_APP_I ON INV_APP_INFORMATION_SYSTEM_DB (APPLICATION_ID) TABLESPACE INVAI_INDEX;

CREATE INDEX INV_APP_SYSTEM_ISDB_I ON INV_APP_SYSTEM (INFORMATION_SYSTEM_DB) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_SYSTEM_SYS_I ON INV_APP_SYSTEM (SYSTEM_ID) TABLESPACE INVAI_INDEX;

CREATE INDEX INV_APP_DB_ISDB_I ON INV_APP_DATABASE (INFORMATION_SYSTEM_DB) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_DB_DB_I ON INV_APP_DATABASE (DATABASE_ID) TABLESPACE INVAI_INDEX;

CREATE INDEX INV_APP_DEV_APP_I ON INV_APP_DEVELOPMENT (APPLICATION_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_DEV_ENV_I ON INV_APP_DEVELOPMENT (ENVIRONMENT_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_DEV_MOD_I ON INV_APP_DEVELOPMENT (MODALITY_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_DEV_STD_I ON INV_APP_DEVELOPMENT (STANDARD_ADAPTION) TABLESPACE INVAI_INDEX;

CREATE INDEX INV_APP_PROV_DEV_I ON INV_APP_PROVIDER (APP_DEVELOPMENT_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_PROV_ROLE_I ON INV_APP_PROVIDER (ROLE) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_TECH_DEV_I ON INV_APP_TECHNOLOGY (APP_DEVELOPMENT_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_TECH_LAYER_I ON INV_APP_TECHNOLOGY (LAYER) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_TECH_TECH_I ON INV_APP_TECHNOLOGY (TECHNOLOGY) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_TECHNOLOGY_LAYER_I ON INV_TECHNOLOGY (LAYER) TABLESPACE INVAI_INDEX;