ALTER TABLE INV_ENVIRONMENT
    ADD CONSTRAINT INV_ENVIRONMENT_PK PRIMARY KEY (ID) USING INDEX INV_ENV_PK_I;
ALTER TABLE INV_ENVIRONMENT_AUD
    ADD CONSTRAINT INV_ENVIRONMENT_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_ENV_AUD_PK_I;

ALTER TABLE INV_LKUP_SERVER_TYPE
    ADD CONSTRAINT INV_LKUP_SERVER_TYPE_PK PRIMARY KEY (ID) USING INDEX INV_LKUP_SERVER_TYPE_PK_I;
ALTER TABLE INV_LKUP_SERVER_TYPE
    ADD CONSTRAINT INV_LKUP_SERVER_TYPE_CODE_UK UNIQUE (CODE) USING INDEX INV_LKUP_SERVER_TYPE_CODE_UK_I;

ALTER TABLE INV_SERVER
    ADD CONSTRAINT INV_SERVER_PK PRIMARY KEY (ID) USING INDEX INV_SERVER_PK_I;
ALTER TABLE INV_SERVER
    ADD CONSTRAINT INV_SERVER_UK UNIQUE (ID, NAME) USING INDEX INV_SERVER_UK_I;
ALTER TABLE INV_SERVER_AUD
    ADD CONSTRAINT INV_SERVER_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_SERVER_AUD_PK_I;

ALTER TABLE INV_SYSTEM
    ADD CONSTRAINT INV_SYSTEM_PK PRIMARY KEY (ID) USING INDEX INV_SYSTEM_PK_I;
ALTER TABLE INV_SYSTEM_AUD
    ADD CONSTRAINT INV_SYSTEM_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_SYSTEM_AUD_PK_I;


ALTER TABLE INV_DATABASE_VENDOR
    ADD CONSTRAINT INV_DATABASE_VENDOR_PK PRIMARY KEY (ID) USING INDEX INV_DATABASE_VENDOR_PK_I;
ALTER TABLE INV_DATABASE_VENDOR_AUD
    ADD CONSTRAINT INV_DATABASE_VENDOR_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_DB_VENDOR_AUD_PK_I;

ALTER TABLE INV_DATABASE
    ADD CONSTRAINT INV_DATABASE_PK PRIMARY KEY (ID) USING INDEX INV_DATABASE_PK_I;
ALTER TABLE INV_DATABASE_AUD
    ADD CONSTRAINT INV_DATABASE_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_DATABASE_AUD_PK_I;

ALTER TABLE INV_APP_INFORMATION_SYSTEM_DB
    ADD CONSTRAINT INV_APP_INF_SYS_DB_PK PRIMARY KEY (ID) USING INDEX INV_APP_INF_SYS_DB_PK_I;
ALTER TABLE INV_APP_INFORMATION_SYSTEM_DB_AUD
    ADD CONSTRAINT INV_APP_INF_SYS_DB_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_INF_SYS_DB_AUD_PK_I;

ALTER TABLE INV_APP_SYSTEM
    ADD CONSTRAINT INV_APP_SYSTEM_PK PRIMARY KEY (ID) USING INDEX INV_APP_SYSTEM_PK_I;
ALTER TABLE INV_APP_SYSTEM_AUD
    ADD CONSTRAINT INV_APP_SYSTEM_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_SYSTEM_AUD_PK_I;

ALTER TABLE INV_APP_DATABASE
    ADD CONSTRAINT INV_APP_DATABASE_PK PRIMARY KEY (ID) USING INDEX INV_APP_DATABASE_PK_I;
ALTER TABLE INV_APP_DATABASE_AUD
    ADD CONSTRAINT INV_APP_DATABASE_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_DATABASE_AUD_PK_I;

ALTER TABLE INV_LKUP_MODALITY
    ADD CONSTRAINT INV_LKUP_MODALITY_PK PRIMARY KEY (ID) USING INDEX INV_LKUP_MODALITY_PK_I;
ALTER TABLE INV_LKUP_STANDARD_ADAPTION
    ADD CONSTRAINT INV_STD_ADAPTION_LKUP_PK PRIMARY KEY (ID) USING INDEX INV_STD_ADAPT_LKUP_PK_I;

ALTER TABLE INV_APP_DEVELOPMENT
    ADD CONSTRAINT INV_APP_DEVELOPMENT_PK PRIMARY KEY (ID) USING INDEX INV_APP_DEV_PK_I;
ALTER TABLE INV_APP_DEVELOPMENT_AUD
    ADD CONSTRAINT INV_APP_DEVELOPMENT_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_DEV_AUD_PK_I;

ALTER TABLE INV_APP_PROVIDER
    ADD CONSTRAINT INV_APP_PROVIDER_PK PRIMARY KEY (ID) USING INDEX INV_APP_PROVIDER_PK_I;
ALTER TABLE INV_APP_PROVIDER_AUD
    ADD CONSTRAINT INV_APP_PROVIDER_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_PROVIDER_AUD_PK_I;

ALTER TABLE INV_APP_TECHNOLOGY
    ADD CONSTRAINT INV_APP_TECHNOLOGY_PK PRIMARY KEY (ID) USING INDEX INV_APP_TECH_PK_I;
ALTER TABLE INV_APP_TECHNOLOGY_AUD
    ADD CONSTRAINT INV_APP_TECHNOLOGY_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_TECH_AUD_PK_I;

ALTER TABLE INV_ROLE
    ADD CONSTRAINT INV_ROLE_PK PRIMARY KEY (ID) USING INDEX INV_ROLE_PK_I;
ALTER TABLE INV_ROLE_AUD
    ADD CONSTRAINT INV_ROLE_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_ROLE_AUD_PK_I;

ALTER TABLE INV_LAYER
    ADD CONSTRAINT INV_LAYER_PK PRIMARY KEY (ID) USING INDEX INV_LAYER_PK_I;
ALTER TABLE INV_LAYER_AUD
    ADD CONSTRAINT INV_LAYER_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_LAYER_AUD_PK_I;

ALTER TABLE INV_TECHNOLOGY
    ADD CONSTRAINT INV_TECHNOLOGY_PK PRIMARY KEY (ID) USING INDEX INV_TECHNOLOGY_PK_I;
ALTER TABLE INV_TECHNOLOGY_AUD
    ADD CONSTRAINT INV_TECHNOLOGY_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_TECHNOLOGY_AUD_PK_I;

ALTER TABLE INV_SERVER
    ADD CONSTRAINT INV_SERVER_ENV_FK FOREIGN KEY (ENVIRONMENT_ID) REFERENCES INV_ENVIRONMENT (ID);
ALTER TABLE INV_SERVER
    ADD CONSTRAINT INV_SERVER_TYPE_FK FOREIGN KEY (SERVER_TYPE_ID) REFERENCES INV_LKUP_SERVER_TYPE (ID);
ALTER TABLE INV_SYSTEM
    ADD CONSTRAINT INV_SYS_SERVER_FK FOREIGN KEY (SERVER_ID) REFERENCES INV_SERVER (ID);

ALTER TABLE INV_DATABASE
    ADD CONSTRAINT INV_DATABASE_SERVER_FK FOREIGN KEY (SERVER_ID) REFERENCES INV_SERVER (ID);
ALTER TABLE INV_DATABASE
    ADD CONSTRAINT INV_DATABASE_TYPE_FK FOREIGN KEY (DATABASE_TYPE) REFERENCES INV_DATABASE_VENDOR (ID);

ALTER TABLE INV_APP_INFORMATION_SYSTEM_DB
    ADD CONSTRAINT INV_APP_INF_SYS_DB_APP_FK FOREIGN KEY (APPLICATION_ID) REFERENCES INV_APPLICATION (APP_APPLICATION_ID);

ALTER TABLE INV_APP_SYSTEM
    ADD CONSTRAINT INV_APP_SYSTEM_ISDB_FK FOREIGN KEY (INFORMATION_SYSTEM_DB) REFERENCES INV_APP_INFORMATION_SYSTEM_DB (ID);
ALTER TABLE INV_APP_SYSTEM
    ADD CONSTRAINT INV_APP_SYSTEM_SYS_FK FOREIGN KEY (SYSTEM_ID) REFERENCES INV_SYSTEM (ID);

ALTER TABLE INV_APP_DATABASE
    ADD CONSTRAINT INV_APP_DB_ISDB_FK FOREIGN KEY (INFORMATION_SYSTEM_DB) REFERENCES INV_APP_INFORMATION_SYSTEM_DB (ID);
ALTER TABLE INV_APP_DATABASE
    ADD CONSTRAINT INV_APP_DB_DB_FK FOREIGN KEY (DATABASE_ID) REFERENCES INV_DATABASE (ID);

ALTER TABLE INV_APP_DEVELOPMENT
    ADD CONSTRAINT INV_APP_DEV_APP_FK FOREIGN KEY (APPLICATION_ID) REFERENCES INV_APPLICATION (APP_APPLICATION_ID);
ALTER TABLE INV_APP_DEVELOPMENT
    ADD CONSTRAINT INV_APP_DEV_ENV_FK FOREIGN KEY (ENVIRONMENT_ID) REFERENCES INV_ENVIRONMENT (ID);
ALTER TABLE INV_APP_DEVELOPMENT
    ADD CONSTRAINT INV_APP_DEV_MOD_FK FOREIGN KEY (MODALITY_ID) REFERENCES INV_LKUP_MODALITY (ID);
ALTER TABLE INV_APP_DEVELOPMENT
    ADD CONSTRAINT INV_APP_DEV_STD_FK FOREIGN KEY (STANDARD_ADAPTION) REFERENCES INV_LKUP_STANDARD_ADAPTION (ID);

ALTER TABLE INV_APP_PROVIDER
    ADD CONSTRAINT INV_APP_PROV_DEV_FK FOREIGN KEY (APP_DEVELOPMENT_ID) REFERENCES INV_APP_DEVELOPMENT (ID);
ALTER TABLE INV_APP_PROVIDER
    ADD CONSTRAINT INV_APP_PROV_ROLE_FK FOREIGN KEY (ROLE) REFERENCES INV_ROLE (ID);
ALTER TABLE INV_APP_TECHNOLOGY
    ADD CONSTRAINT INV_APP_TECH_DEV_FK FOREIGN KEY (APP_DEVELOPMENT_ID) REFERENCES INV_APP_DEVELOPMENT (ID);
ALTER TABLE INV_APP_TECHNOLOGY
    ADD CONSTRAINT INV_APP_TECH_LAYER_FK FOREIGN KEY (LAYER) REFERENCES INV_LAYER (ID);
ALTER TABLE INV_APP_TECHNOLOGY
    ADD CONSTRAINT INV_APP_TECH_TECH_FK FOREIGN KEY (TECHNOLOGY) REFERENCES INV_TECHNOLOGY (ID);
ALTER TABLE INV_TECHNOLOGY
    ADD CONSTRAINT INV_TECHNOLOGY_LAYER_FK FOREIGN KEY (LAYER) REFERENCES INV_LAYER (ID);