INSERT INTO INV_ENVIRONMENT (ID, CODE, NAME, NAME_ES, CREATED_AT, CREATED_BY)
SELECT INV_ENVIRONMENT_SEQ.nextval, 'PRO', 'Producció', 'Producción', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_ENVIRONMENT WHERE CODE = 'PRO');

INSERT INTO INV_ENVIRONMENT_AUD (AUDIT_ID, ENVIRONMENT_ID, CODE, NAME, NAME_ES, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_ENVIRONMENT_AUD_SEQ.nextval,
       (SELECT ID FROM INV_ENVIRONMENT WHERE CODE = 'PRO'),
       'PRO', 'Producció', 'Producción', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_ENVIRONMENT_AUD WHERE CODE = 'PRO' AND AUD_ACTION = 'INSERT');

INSERT INTO INV_ENVIRONMENT (ID, CODE, NAME, NAME_ES, CREATED_AT, CREATED_BY)
SELECT INV_ENVIRONMENT_SEQ.nextval, 'PRE', 'Pre-producció', 'Pre-producción', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_ENVIRONMENT WHERE CODE = 'PRE');

INSERT INTO INV_ENVIRONMENT_AUD (AUDIT_ID, ENVIRONMENT_ID, CODE, NAME, NAME_ES, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_ENVIRONMENT_AUD_SEQ.nextval,
       (SELECT ID FROM INV_ENVIRONMENT WHERE CODE = 'PRE'),
       'PRE', 'Pre-producció', 'Pre-producción', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_ENVIRONMENT_AUD WHERE CODE = 'PRE' AND AUD_ACTION = 'INSERT');

INSERT INTO INV_ENVIRONMENT (ID, CODE, NAME, NAME_ES, CREATED_AT, CREATED_BY)
SELECT INV_ENVIRONMENT_SEQ.nextval, 'DEV', 'Desenvolupament', 'Desarrollo', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_ENVIRONMENT WHERE CODE = 'DEV');

INSERT INTO INV_ENVIRONMENT_AUD (AUDIT_ID, ENVIRONMENT_ID, CODE, NAME, NAME_ES, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_ENVIRONMENT_AUD_SEQ.nextval,
       (SELECT ID FROM INV_ENVIRONMENT WHERE CODE = 'DEV'),
       'DEV', 'Desenvolupament', 'Desarrollo', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_ENVIRONMENT_AUD WHERE CODE = 'DEV' AND AUD_ACTION = 'INSERT');

INSERT INTO INV_LKUP_MODALITY (ID, NAME, NAME_ES)
VALUES (INV_LKUP_MODALITY_SEQ.nextval, 'Desenvolupament Intern', 'Desarrollo Interno');

INSERT INTO INV_LKUP_MODALITY (ID, NAME, NAME_ES)
VALUES (INV_LKUP_MODALITY_SEQ.nextval, 'Desenvolupament Extern', 'Desarrollo Externo');

INSERT INTO INV_LKUP_MODALITY (ID, NAME, NAME_ES)
VALUES (INV_LKUP_MODALITY_SEQ.nextval, 'Desenvolupament Mixt', 'Desarrollo Mixto');

INSERT INTO INV_LKUP_STANDARD_ADAPTION (ID, NAME, NAME_ES)
VALUES (INV_LKUP_STANDARD_ADAPTION_SEQ.nextval, 'Conforme', 'Conforme');

INSERT INTO INV_LKUP_STANDARD_ADAPTION (ID, NAME, NAME_ES)
VALUES (INV_LKUP_STANDARD_ADAPTION_SEQ.nextval, 'Parcialment Conforme', 'Parcialmente Conforme');

INSERT INTO INV_LKUP_STANDARD_ADAPTION (ID, NAME, NAME_ES)
VALUES (INV_LKUP_STANDARD_ADAPTION_SEQ.nextval, 'No Conforme', 'No Conforme');

INSERT INTO INV_LKUP_SERVER_TYPE (ID, CODE, NAME, NAME_ES)
VALUES (INV_LKUP_SERVER_TYPE_SEQ.nextval, 'DATABASE', 'Base de dades', 'Base de datos');

INSERT INTO INV_LKUP_SERVER_TYPE (ID, CODE, NAME, NAME_ES)
VALUES (INV_LKUP_SERVER_TYPE_SEQ.nextval, 'APPLICATION', 'Aplicació', 'Aplicación');

INSERT INTO INV_SERVER (ID, NAME, ENVIRONMENT_ID, SERVER_TYPE_ID, CREATED_AT, CREATED_BY)
VALUES (INV_SERVER_SEQ.nextval, 'SRV-APP-01',
        (SELECT ID FROM INV_ENVIRONMENT WHERE CODE = 'PRO'),
        (SELECT ID FROM INV_LKUP_SERVER_TYPE WHERE CODE = 'APPLICATION'),
        SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_SERVER_AUD (AUDIT_ID, SERVER_ID, NAME, ENVIRONMENT_ID, SERVER_TYPE_ID, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_SERVER_AUD_SEQ.nextval, INV_SERVER_SEQ.currval, 'SRV-APP-01',
        (SELECT ID FROM INV_ENVIRONMENT WHERE CODE = 'PRO'),
        (SELECT ID FROM INV_LKUP_SERVER_TYPE WHERE CODE = 'APPLICATION'),
        SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_SERVER (ID, NAME, ENVIRONMENT_ID, SERVER_TYPE_ID, CREATED_AT, CREATED_BY)
VALUES (INV_SERVER_SEQ.nextval, 'SRV-BD-01',
        (SELECT ID FROM INV_ENVIRONMENT WHERE CODE = 'PRO'),
        (SELECT ID FROM INV_LKUP_SERVER_TYPE WHERE CODE = 'DATABASE'),
        SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_SERVER_AUD (AUDIT_ID, SERVER_ID, NAME, ENVIRONMENT_ID, SERVER_TYPE_ID, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_SERVER_AUD_SEQ.nextval, INV_SERVER_SEQ.currval, 'SRV-BD-01',
        (SELECT ID FROM INV_ENVIRONMENT WHERE CODE = 'PRO'),
        (SELECT ID FROM INV_LKUP_SERVER_TYPE WHERE CODE = 'DATABASE'),
        SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_SYSTEM (ID, SERVER_ID, INSTANCE, PORT, VERSION, DESCRIPTION, CREATED_AT, CREATED_BY)
VALUES (INV_SYSTEM_SEQ.nextval,
        (SELECT ID FROM INV_SERVER WHERE NAME = 'SRV-APP-01'),
        'tomcat-prod-01', 8080, '9.0.80', 'Servidor de aplicaciones principal',
        SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_SYSTEM_AUD (AUDIT_ID, SYSTEM_ID, SERVER_ID, INSTANCE, PORT, VERSION, DESCRIPTION, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_SYSTEM_AUD_SEQ.nextval, INV_SYSTEM_SEQ.currval,
        (SELECT ID FROM INV_SERVER WHERE NAME = 'SRV-APP-01'),
        'tomcat-prod-01', 8080, '9.0.80', 'Servidor de aplicaciones principal',
        SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_DATABASE_VENDOR (ID, NAME, DEFAULT_PORT, CREATED_AT, CREATED_BY)
VALUES (INV_DATABASE_VENDOR_SEQ.nextval, 'Oracle', 1521, SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_DATABASE (ID, SERVER_ID, SERVICE, PORT, DATABASE_TYPE, DESCRIPTION, CREATED_AT, CREATED_BY)
VALUES (INV_DATABASE_SEQ.nextval,
        (SELECT ID FROM INV_SERVER WHERE NAME = 'SRV-BD-01'),
        'ORCL_PROD', 1521,
        (SELECT ID FROM INV_DATABASE_VENDOR WHERE NAME = 'Oracle'),
        'Base de datos central de producción', SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_DATABASE_AUD (AUDIT_ID, DATABASE_ID, SERVER_ID, SERVICE, PORT, DATABASE_TYPE, DESCRIPTION, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_DATABASE_AUD_SEQ.nextval, INV_DATABASE_SEQ.currval,
        (SELECT ID FROM INV_SERVER WHERE NAME = 'SRV-BD-01'), 'ORCL_PROD',
        1521, (SELECT ID FROM INV_DATABASE_VENDOR WHERE NAME = 'Oracle'),
        'Base de datos central de producción', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_APP_INFORMATION_SYSTEM_DB (ID, APPLICATION_ID, OBSERVATION, CREATED_AT, CREATED_BY)
VALUES (INV_APP_INF_SYS_DB_SEQ.nextval,
        (SELECT APP_APPLICATION_ID FROM INV_APPLICATION WHERE CODE = 'APP-001'),
        'Asignación inicial de infraestructura a la aplicación APP-001',
        SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_APP_INFORMATION_SYSTEM_DB_AUD (AUDIT_ID, ID, APPLICATION_ID, OBSERVATION, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_APP_INF_SYS_DB_AUD_SEQ.nextval,
        INV_APP_INF_SYS_DB_SEQ.currval,
        (SELECT APP_APPLICATION_ID FROM INV_APPLICATION WHERE CODE = 'APP-001'),
        'Asignación inicial de infraestructura a la aplicación APP-001',
        SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_APP_SYSTEM (ID, INFORMATION_SYSTEM_DB, SYSTEM_ID, CREATED_AT, CREATED_BY)
VALUES (INV_APP_SYSTEM_SEQ.nextval,
        INV_APP_INF_SYS_DB_SEQ.currval,
        (SELECT ID FROM INV_SYSTEM WHERE SERVER_ID = (SELECT ID FROM INV_SERVER WHERE NAME = 'SRV-APP-01')),
        SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_APP_SYSTEM_AUD (AUDIT_ID, APP_SYSTEM_ID, INFORMATION_SYSTEM_DB, SYSTEM_ID, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_APP_SYSTEM_AUD_SEQ.nextval,
        INV_APP_SYSTEM_SEQ.currval,
        INV_APP_INF_SYS_DB_SEQ.currval,
        (SELECT ID FROM INV_SYSTEM WHERE SERVER_ID = (SELECT ID FROM INV_SERVER WHERE NAME = 'SRV-APP-01')),
        SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_APP_DATABASE (ID, INFORMATION_SYSTEM_DB, DATABASE_ID, CREATED_AT, CREATED_BY)
VALUES (INV_APP_DATABASE_SEQ.nextval,
        INV_APP_INF_SYS_DB_SEQ.currval,
        (SELECT ID FROM INV_DATABASE WHERE SERVICE = 'ORCL_PROD'),
        SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_APP_DATABASE_AUD (AUDIT_ID, APP_DATABASE_ID, INFORMATION_SYSTEM_DB, DATABASE_ID, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_APP_DATABASE_AUD_SEQ.nextval,
        INV_APP_DATABASE_SEQ.currval,
        INV_APP_INF_SYS_DB_SEQ.currval,
        (SELECT ID FROM INV_DATABASE WHERE SERVICE = 'ORCL_PROD'),
        SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_APP_DEVELOPMENT (ID, APPLICATION_ID, ENVIRONMENT_ID, MODALITY_ID, CODE, STANDARD_ADAPTION, REVISION_DATE, OBSERVATION, CREATED_AT, CREATED_BY)
VALUES (INV_APP_DEVELOPMENT_SEQ.nextval,
        (SELECT APP_APPLICATION_ID FROM INV_APPLICATION WHERE CODE = 'APP-001'),
        (SELECT ID FROM INV_ENVIRONMENT WHERE CODE = 'PRO'),
        (SELECT ID FROM INV_LKUP_MODALITY WHERE NAME_ES = 'Desarrollo Externo'),
        'https://git.internal.example.org/apps/app-001.git',
        (SELECT ID FROM INV_LKUP_STANDARD_ADAPTION WHERE NAME_ES = 'Conforme'),
        SYSTIMESTAMP,
        'Registro inicial de desarrollo para el entorno de producción.',
        SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_APP_DEVELOPMENT_AUD (AUDIT_ID, APP_DEVELOPMENT_ID, APPLICATION_ID, ENVIRONMENT_ID, MODALITY_ID, CODE, STANDARD_ADAPTION, REVISION_DATE, OBSERVATION, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_APP_DEVELOPMENT_AUD_SEQ.nextval,
        INV_APP_DEVELOPMENT_SEQ.currval,
        (SELECT APP_APPLICATION_ID FROM INV_APPLICATION WHERE CODE = 'APP-001'),
        (SELECT ID FROM INV_ENVIRONMENT WHERE CODE = 'PRO'),
        (SELECT ID FROM INV_LKUP_MODALITY WHERE NAME_ES = 'Desarrollo Externo'),
        'https://git.internal.example.org/apps/app-001.git',
        (SELECT ID FROM INV_LKUP_STANDARD_ADAPTION WHERE NAME_ES = 'Conforme'),
        SYSTIMESTAMP,
        'Registro inicial de desarrollo para el entorno de producción.',
        SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_ROLE (ID, NAME, NAME_ES, CREATED_AT, CREATED_BY)
SELECT INV_ROLE_SEQ.nextval, 'Proveïdor principal', 'Proveedor principal', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_ROLE WHERE NAME = 'Proveïdor principal');

INSERT INTO INV_ROLE_AUD (AUDIT_ID, ROLE_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_ROLE_AUD_SEQ.nextval,
       (SELECT ID FROM INV_ROLE WHERE NAME = 'Proveïdor principal'),
       'Proveïdor principal', 'Proveedor principal', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_ROLE_AUD WHERE NAME = 'Proveïdor principal' AND AUD_ACTION = 'INSERT');

INSERT INTO INV_ROLE (ID, NAME, NAME_ES, CREATED_AT, CREATED_BY)
SELECT INV_ROLE_SEQ.nextval, 'Proveïdor secundari', 'Proveedor secundario', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_ROLE WHERE NAME = 'Proveïdor secundari');

INSERT INTO INV_ROLE_AUD (AUDIT_ID, ROLE_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_ROLE_AUD_SEQ.nextval,
       (SELECT ID FROM INV_ROLE WHERE NAME = 'Proveïdor secundari'),
       'Proveïdor secundari', 'Proveedor secundario', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_ROLE_AUD WHERE NAME = 'Proveïdor secundari' AND AUD_ACTION = 'INSERT');

INSERT INTO INV_LAYER (ID, NAME, CREATED_AT, CREATED_BY)
SELECT INV_LAYER_SEQ.nextval, 'Backend', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_LAYER WHERE NAME = 'Backend');

INSERT INTO INV_LAYER_AUD (AUDIT_ID, LAYER_ID, NAME, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_LAYER_AUD_SEQ.nextval,
       (SELECT ID FROM INV_LAYER WHERE NAME = 'Backend'),
       'Backend', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_LAYER_AUD WHERE NAME = 'Backend' AND AUD_ACTION = 'INSERT');

INSERT INTO INV_LAYER (ID, NAME, CREATED_AT, CREATED_BY)
SELECT INV_LAYER_SEQ.nextval, 'Frontend', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_LAYER WHERE NAME = 'Frontend');

INSERT INTO INV_LAYER_AUD (AUDIT_ID, LAYER_ID, NAME, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_LAYER_AUD_SEQ.nextval,
       (SELECT ID FROM INV_LAYER WHERE NAME = 'Frontend'),
       'Frontend', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_LAYER_AUD WHERE NAME = 'Frontend' AND AUD_ACTION = 'INSERT');

INSERT INTO INV_TECHNOLOGY (ID, NAME, LAYER, CREATED_AT, CREATED_BY)
SELECT INV_TECHNOLOGY_SEQ.nextval, 'Spring Boot', (SELECT ID FROM INV_LAYER WHERE NAME = 'Backend'), SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_TECHNOLOGY WHERE NAME = 'Spring Boot');

INSERT INTO INV_TECHNOLOGY_AUD (AUDIT_ID, TECHNOLOGY_ID, NAME, LAYER_ID, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_TECHNOLOGY_AUD_SEQ.nextval,
       (SELECT ID FROM INV_TECHNOLOGY WHERE NAME = 'Spring Boot'),
       'Spring Boot', (SELECT ID FROM INV_LAYER WHERE NAME = 'Backend'), SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_TECHNOLOGY_AUD WHERE NAME = 'Spring Boot' AND AUD_ACTION = 'INSERT');

INSERT INTO INV_TECHNOLOGY (ID, NAME, LAYER, CREATED_AT, CREATED_BY)
SELECT INV_TECHNOLOGY_SEQ.nextval, 'Angular', (SELECT ID FROM INV_LAYER WHERE NAME = 'Frontend'), SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_TECHNOLOGY WHERE NAME = 'Angular');

INSERT INTO INV_TECHNOLOGY_AUD (AUDIT_ID, TECHNOLOGY_ID, NAME, LAYER_ID, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_TECHNOLOGY_AUD_SEQ.nextval,
       (SELECT ID FROM INV_TECHNOLOGY WHERE NAME = 'Angular'),
       'Angular', (SELECT ID FROM INV_LAYER WHERE NAME = 'Frontend'), SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_TECHNOLOGY_AUD WHERE NAME = 'Angular' AND AUD_ACTION = 'INSERT');

INSERT INTO INV_APP_PROVIDER (ID, APP_DEVELOPMENT_ID, COMPANY_NAME, ROLE, START_DATE, EXPIRE_DATE, CREATED_AT, CREATED_BY)
VALUES (INV_APP_PROVIDER_SEQ.nextval,
        INV_APP_DEVELOPMENT_SEQ.currval,
        'Plexus tech',
        (SELECT ID FROM INV_ROLE WHERE NAME = 'Proveïdor principal'),
        SYSTIMESTAMP,
        ADD_MONTHS(SYSTIMESTAMP, 12),
        SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_APP_PROVIDER_AUD (AUDIT_ID, APP_PROVIDER_ID, APP_DEVELOPMENT_ID, COMPANY_NAME, ROLE, START_DATE, EXPIRE_DATE, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_APP_PROVIDER_AUD_SEQ.nextval,
        INV_APP_PROVIDER_SEQ.currval,
        INV_APP_DEVELOPMENT_SEQ.currval,
        'Plexus tech',
        (SELECT ID FROM INV_ROLE WHERE NAME = 'Proveïdor principal'),
        SYSTIMESTAMP,
        ADD_MONTHS(SYSTIMESTAMP, 12),
        SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_APP_TECHNOLOGY (ID, APP_DEVELOPMENT_ID, LAYER, TECHNOLOGY, VERSION, ARCHITECTURE, CREATED_AT, CREATED_BY)
VALUES (INV_APP_TECHNOLOGY_SEQ.nextval,
        INV_APP_DEVELOPMENT_SEQ.currval,
        (SELECT ID FROM INV_LAYER WHERE NAME = 'Backend'),
        (SELECT ID FROM INV_TECHNOLOGY WHERE NAME = 'Spring Boot'),
        '3.2.1', 'Microservicios REST',
        SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_APP_TECHNOLOGY_AUD (AUDIT_ID, APP_TECHNOLOGY_ID, APP_DEVELOPMENT_ID, LAYER, TECHNOLOGY, VERSION, ARCHITECTURE, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_APP_TECHNOLOGY_AUD_SEQ.nextval,
        INV_APP_TECHNOLOGY_SEQ.currval,
        INV_APP_DEVELOPMENT_SEQ.currval,
        (SELECT ID FROM INV_LAYER WHERE NAME = 'Backend'),
        (SELECT ID FROM INV_TECHNOLOGY WHERE NAME = 'Spring Boot'),
        '3.2.1', 'Microservicios REST',
        SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_APP_TECHNOLOGY (ID, APP_DEVELOPMENT_ID, LAYER, TECHNOLOGY, VERSION, ARCHITECTURE, CREATED_AT, CREATED_BY)
VALUES (INV_APP_TECHNOLOGY_SEQ.nextval,
        INV_APP_DEVELOPMENT_SEQ.currval,
        (SELECT ID FROM INV_LAYER WHERE NAME = 'Frontend'),
        (SELECT ID FROM INV_TECHNOLOGY WHERE NAME = 'Angular'),
        '17.0.0', 'Single Page Application (SPA)',
        SYSTIMESTAMP, 'ADMIN');

INSERT INTO INV_APP_TECHNOLOGY_AUD (AUDIT_ID, APP_TECHNOLOGY_ID, APP_DEVELOPMENT_ID, LAYER, TECHNOLOGY, VERSION, ARCHITECTURE, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
VALUES (INV_APP_TECHNOLOGY_AUD_SEQ.nextval,
        INV_APP_TECHNOLOGY_SEQ.currval,
        INV_APP_DEVELOPMENT_SEQ.currval,
        (SELECT ID FROM INV_LAYER WHERE NAME = 'Frontend'),
        (SELECT ID FROM INV_TECHNOLOGY WHERE NAME = 'Angular'),
        '17.0.0', 'Single Page Application (SPA)',
        SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN');

COMMIT;