CREATE SEQUENCE INV_COMPANY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE INV_PERSON_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE INV_AUTHORIZATION_TYPE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE INV_LKUP_RESPONSIBLE_TYPE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE INV_APP_RESPONSIBLE_AUTHORIZED_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE INV_APP_RESPONSIBLE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE INV_APP_AUTHORIZED_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE INV_APP_AUTHORIZED_TYPE_LINK_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE INV_COMPANY_AUD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE INV_PERSON_AUD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE INV_AUTHORIZATION_TYPE_AUD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE INV_APP_RESPONSIBLE_AUTHORIZED_AUD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE INV_APP_RESPONSIBLE_AUD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE INV_APP_AUTHORIZED_AUD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
