CREATE UNIQUE INDEX INV_COMPANY_PK_I ON INV_COMPANY (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_PERSON_PK_I ON INV_PERSON (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_AUTHORIZATION_TYPE_PK_I ON INV_AUTHORIZATION_TYPE (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_LKUP_RESPONSIBLE_TYPE_PK_I ON INV_LKUP_RESPONSIBLE_TYPE (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_RESP_AUTH_PK_I ON INV_APP_RESPONSIBLE_AUTHORIZED (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_RESP_PK_I ON INV_APP_RESPONSIBLE (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_AUTHORIZED_PK_I ON INV_APP_AUTHORIZED (ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_AUTH_TYPE_LINK_PK_I ON INV_APP_AUTHORIZED_TYPE_LINK (ID) TABLESPACE INVAI_INDEX;

CREATE UNIQUE INDEX INV_COMPANY_AUD_PK_I ON INV_COMPANY_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_PERSON_AUD_PK_I ON INV_PERSON_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_AUTH_TYPE_AUD_PK_I ON INV_AUTHORIZATION_TYPE_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_RESP_AUTH_AUD_PK_I ON INV_APP_RESPONSIBLE_AUTHORIZED_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_RESP_AUD_PK_I ON INV_APP_RESPONSIBLE_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APP_AUTHORIZED_AUD_PK_I ON INV_APP_AUTHORIZED_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;

CREATE INDEX INV_PERSON_COMPANY_I ON INV_PERSON (COMPANY_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_RESP_AUTH_APP_I ON INV_APP_RESPONSIBLE_AUTHORIZED (APPLICATION_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_RESP_APPRESP_I ON INV_APP_RESPONSIBLE (APP_RESPONSIBLE_AUTHORIZED_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_RESP_PERSON_I ON INV_APP_RESPONSIBLE (PERSON_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_RESP_TYPE_I ON INV_APP_RESPONSIBLE (RESPONSIBLE_TYPE_ID) TABLESPACE INVAI_INDEX;


CREATE UNIQUE INDEX INV_APP_RESP_TYPE_ACTIVE_UK_I ON INV_APP_RESPONSIBLE (APP_RESPONSIBLE_AUTHORIZED_ID,
                                                                          RESPONSIBLE_TYPE_ID, CASE
                                                                                                   WHEN DELETED_AT IS NULL
                                                                                                       THEN 0 END) TABLESPACE INVAI_INDEX;

CREATE INDEX INV_APP_AUTHORIZED_APPRESP_I ON INV_APP_AUTHORIZED (APP_RESPONSIBLE_AUTHORIZED_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_AUTHORIZED_PERSON_I ON INV_APP_AUTHORIZED (PERSON_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_AUTH_TYPE_LINK_ANCHOR_I ON INV_APP_AUTHORIZED_TYPE_LINK (APP_AUTHORIZED_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APP_AUTH_TYPE_LINK_TYPE_I ON INV_APP_AUTHORIZED_TYPE_LINK (AUTHORIZATION_TYPE_ID) TABLESPACE INVAI_INDEX;
