ALTER TABLE INV_COMPANY
    ADD CONSTRAINT INV_COMPANY_PK PRIMARY KEY (ID) USING INDEX INV_COMPANY_PK_I;
ALTER TABLE INV_COMPANY_AUD
    ADD CONSTRAINT INV_COMPANY_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_COMPANY_AUD_PK_I;

ALTER TABLE INV_PERSON
    ADD CONSTRAINT INV_PERSON_PK PRIMARY KEY (ID) USING INDEX INV_PERSON_PK_I;
ALTER TABLE INV_PERSON_AUD
    ADD CONSTRAINT INV_PERSON_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_PERSON_AUD_PK_I;

ALTER TABLE INV_AUTHORIZATION_TYPE
    ADD CONSTRAINT INV_AUTHORIZATION_TYPE_PK PRIMARY KEY (ID) USING INDEX INV_AUTHORIZATION_TYPE_PK_I;
ALTER TABLE INV_AUTHORIZATION_TYPE_AUD
    ADD CONSTRAINT INV_AUTH_TYPE_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_AUTH_TYPE_AUD_PK_I;

ALTER TABLE INV_LKUP_RESPONSIBLE_TYPE
    ADD CONSTRAINT INV_LKUP_RESPONSIBLE_TYPE_PK PRIMARY KEY (ID) USING INDEX INV_LKUP_RESPONSIBLE_TYPE_PK_I;

ALTER TABLE INV_APP_RESPONSIBLE_AUTHORIZED
    ADD CONSTRAINT INV_APP_RESP_AUTH_PK PRIMARY KEY (ID) USING INDEX INV_APP_RESP_AUTH_PK_I;
ALTER TABLE INV_APP_RESPONSIBLE_AUTHORIZED_AUD
    ADD CONSTRAINT INV_APP_RESP_AUTH_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_RESP_AUTH_AUD_PK_I;

ALTER TABLE INV_APP_RESPONSIBLE
    ADD CONSTRAINT INV_APP_RESP_PK PRIMARY KEY (ID) USING INDEX INV_APP_RESP_PK_I;
ALTER TABLE INV_APP_RESPONSIBLE_AUD
    ADD CONSTRAINT INV_APP_RESP_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_RESP_AUD_PK_I;

ALTER TABLE INV_APP_AUTHORIZED
    ADD CONSTRAINT INV_APP_AUTHORIZED_PK PRIMARY KEY (ID) USING INDEX INV_APP_AUTHORIZED_PK_I;
ALTER TABLE INV_APP_AUTHORIZED_AUD
    ADD CONSTRAINT INV_APP_AUTHORIZED_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APP_AUTHORIZED_AUD_PK_I;

ALTER TABLE INV_APP_AUTHORIZED_TYPE_LINK
    ADD CONSTRAINT INV_APP_AUTH_TYPE_LINK_PK PRIMARY KEY (ID) USING INDEX INV_APP_AUTH_TYPE_LINK_PK_I;

ALTER TABLE INV_PERSON
    ADD CONSTRAINT INV_PERSON_COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES INV_COMPANY (ID);

ALTER TABLE INV_APP_RESPONSIBLE_AUTHORIZED
    ADD CONSTRAINT INV_APP_RESP_AUTH_APP_FK FOREIGN KEY (APPLICATION_ID) REFERENCES INV_APPLICATION (APP_APPLICATION_ID);

ALTER TABLE INV_APP_RESPONSIBLE
    ADD CONSTRAINT INV_APP_RESP_APPRESP_FK FOREIGN KEY (APP_RESPONSIBLE_AUTHORIZED_ID) REFERENCES INV_APP_RESPONSIBLE_AUTHORIZED (ID);
ALTER TABLE INV_APP_RESPONSIBLE
    ADD CONSTRAINT INV_APP_RESP_PERSON_FK FOREIGN KEY (PERSON_ID) REFERENCES INV_PERSON (ID);
ALTER TABLE INV_APP_RESPONSIBLE
    ADD CONSTRAINT INV_APP_RESP_TYPE_FK FOREIGN KEY (RESPONSIBLE_TYPE_ID) REFERENCES INV_LKUP_RESPONSIBLE_TYPE (ID);

ALTER TABLE INV_APP_AUTHORIZED
    ADD CONSTRAINT INV_APP_AUTHORIZED_APPRESP_FK FOREIGN KEY (APP_RESPONSIBLE_AUTHORIZED_ID) REFERENCES INV_APP_RESPONSIBLE_AUTHORIZED (ID);
ALTER TABLE INV_APP_AUTHORIZED
    ADD CONSTRAINT INV_APP_AUTHORIZED_PERSON_FK FOREIGN KEY (PERSON_ID) REFERENCES INV_PERSON (ID);

ALTER TABLE INV_APP_AUTHORIZED_TYPE_LINK
    ADD CONSTRAINT INV_APP_AUTH_TYPE_LINK_ANCHOR_FK FOREIGN KEY (APP_AUTHORIZED_ID) REFERENCES INV_APP_AUTHORIZED (ID);
ALTER TABLE INV_APP_AUTHORIZED_TYPE_LINK
    ADD CONSTRAINT INV_APP_AUTH_TYPE_LINK_TYPE_FK FOREIGN KEY (AUTHORIZATION_TYPE_ID) REFERENCES INV_AUTHORIZATION_TYPE (ID);
