GRANT SELECT, INSERT, UPDATE, DELETE ON INV_COMPANY TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_PERSON TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_AUTHORIZATION_TYPE TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_LKUP_RESPONSIBLE_TYPE TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_APP_RESPONSIBLE_AUTHORIZED TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_APP_RESPONSIBLE TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_APP_AUTHORIZED TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_APP_AUTHORIZED_TYPE_LINK TO WWW_INVAI;

GRANT SELECT, INSERT, UPDATE, DELETE ON INV_COMPANY_AUD TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_PERSON_AUD TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_AUTHORIZATION_TYPE_AUD TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_APP_RESPONSIBLE_AUTHORIZED_AUD TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_APP_RESPONSIBLE_AUD TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_APP_AUTHORIZED_AUD TO WWW_INVAI;

GRANT SELECT ON INV_COMPANY_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_PERSON_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_AUTHORIZATION_TYPE_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_LKUP_RESPONSIBLE_TYPE_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_APP_RESPONSIBLE_AUTHORIZED_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_APP_RESPONSIBLE_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_APP_AUTHORIZED_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_APP_AUTHORIZED_TYPE_LINK_SEQ TO WWW_INVAI;

GRANT SELECT ON INV_COMPANY_AUD_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_PERSON_AUD_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_AUTHORIZATION_TYPE_AUD_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_APP_RESPONSIBLE_AUTHORIZED_AUD_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_APP_RESPONSIBLE_AUD_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_APP_AUTHORIZED_AUD_SEQ TO WWW_INVAI;
