INSERT INTO INV_COMPANY (ID, NAME, CREATED_AT, CREATED_BY)
SELECT INV_COMPANY_SEQ.nextval, 'Plexus Tech', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_COMPANY WHERE NAME = 'Plexus Tech');

INSERT INTO INV_COMPANY_AUD (AUDIT_ID, COMPANY_ID, NAME, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_COMPANY_AUD_SEQ.nextval,
       (SELECT ID FROM INV_COMPANY WHERE NAME = 'Plexus Tech'),
       'Plexus Tech', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_COMPANY_AUD WHERE NAME = 'Plexus Tech' AND AUD_ACTION = 'INSERT');

INSERT INTO INV_PERSON (ID, COMPANY_ID, FIRST_NAME, LAST_NAME, EMAIL, CREATED_AT, CREATED_BY)
SELECT INV_PERSON_SEQ.nextval,
       (SELECT ID FROM INV_COMPANY WHERE NAME = 'Plexus Tech'),
       'Joan', 'Puig', 'joan.puig@plexus.example', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_PERSON WHERE EMAIL = 'joan.puig@plexus.example');

INSERT INTO INV_PERSON_AUD (AUDIT_ID, PERSON_ID, COMPANY_ID, FIRST_NAME, LAST_NAME, EMAIL, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_PERSON_AUD_SEQ.nextval,
       (SELECT ID FROM INV_PERSON WHERE EMAIL = 'joan.puig@plexus.example'),
       (SELECT ID FROM INV_COMPANY WHERE NAME = 'Plexus Tech'),
       'Joan', 'Puig', 'joan.puig@plexus.example', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_PERSON_AUD WHERE EMAIL = 'joan.puig@plexus.example' AND AUD_ACTION = 'INSERT');

INSERT INTO INV_AUTHORIZATION_TYPE (ID, NAME, NAME_ES, CREATED_AT, CREATED_BY)
SELECT INV_AUTHORIZATION_TYPE_SEQ.nextval, 'Signar peticions', 'Firmar peticiones', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_AUTHORIZATION_TYPE WHERE NAME_ES = 'Firmar peticiones');

INSERT INTO INV_AUTHORIZATION_TYPE_AUD (AUDIT_ID, AUTHORIZATION_TYPE_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_AUTHORIZATION_TYPE_AUD_SEQ.nextval,
       (SELECT ID FROM INV_AUTHORIZATION_TYPE WHERE NAME_ES = 'Firmar peticiones'),
       'Signar peticions', 'Firmar peticiones', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_AUTHORIZATION_TYPE_AUD WHERE NAME_ES = 'Firmar peticiones' AND AUD_ACTION = 'INSERT');

INSERT INTO INV_AUTHORIZATION_TYPE (ID, NAME, NAME_ES, CREATED_AT, CREATED_BY)
SELECT INV_AUTHORIZATION_TYPE_SEQ.nextval, 'Accés als registres', 'Acceso a los logs', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_AUTHORIZATION_TYPE WHERE NAME_ES = 'Acceso a los logs');

INSERT INTO INV_AUTHORIZATION_TYPE_AUD (AUDIT_ID, AUTHORIZATION_TYPE_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_AUTHORIZATION_TYPE_AUD_SEQ.nextval,
       (SELECT ID FROM INV_AUTHORIZATION_TYPE WHERE NAME_ES = 'Acceso a los logs'),
       'Accés als registres', 'Acceso a los logs', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_AUTHORIZATION_TYPE_AUD WHERE NAME_ES = 'Acceso a los logs' AND AUD_ACTION = 'INSERT');

INSERT INTO INV_AUTHORIZATION_TYPE (ID, NAME, NAME_ES, CREATED_AT, CREATED_BY)
SELECT INV_AUTHORIZATION_TYPE_SEQ.nextval, 'Desplegament d''aplicacions', 'Despliegue de aplicaciones', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_AUTHORIZATION_TYPE WHERE NAME_ES = 'Despliegue de aplicaciones');

INSERT INTO INV_AUTHORIZATION_TYPE_AUD (AUDIT_ID, AUTHORIZATION_TYPE_ID, NAME, NAME_ES, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_AUTHORIZATION_TYPE_AUD_SEQ.nextval,
       (SELECT ID FROM INV_AUTHORIZATION_TYPE WHERE NAME_ES = 'Despliegue de aplicaciones'),
       'Desplegament d''aplicacions', 'Despliegue de aplicaciones', SYSTIMESTAMP, 'ADMIN', 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_AUTHORIZATION_TYPE_AUD WHERE NAME_ES = 'Despliegue de aplicaciones' AND AUD_ACTION = 'INSERT');

INSERT INTO INV_LKUP_RESPONSIBLE_TYPE (ID, NAME, NAME_ES, REQUIRES_PERSONAL_CAIB)
SELECT INV_LKUP_RESPONSIBLE_TYPE_SEQ.nextval, 'Responsable de la informació', 'Responsable de la información', 1
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_LKUP_RESPONSIBLE_TYPE WHERE NAME = 'Responsable de la informació');

INSERT INTO INV_LKUP_RESPONSIBLE_TYPE (ID, NAME, NAME_ES)
SELECT INV_LKUP_RESPONSIBLE_TYPE_SEQ.nextval, 'Responsable del servei', 'Responsable del servicio'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_LKUP_RESPONSIBLE_TYPE WHERE NAME = 'Responsable del servei');

INSERT INTO INV_LKUP_RESPONSIBLE_TYPE (ID, NAME, NAME_ES)
SELECT INV_LKUP_RESPONSIBLE_TYPE_SEQ.nextval, 'Responsable de sistemes', 'Responsable de sistemas'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_LKUP_RESPONSIBLE_TYPE WHERE NAME = 'Responsable de sistemes');

INSERT INTO INV_LKUP_RESPONSIBLE_TYPE (ID, NAME, NAME_ES)
SELECT INV_LKUP_RESPONSIBLE_TYPE_SEQ.nextval, 'Responsable de seguretat', 'Responsable de seguridad'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_LKUP_RESPONSIBLE_TYPE WHERE NAME = 'Responsable de seguretat');

INSERT INTO INV_LKUP_RESPONSIBLE_TYPE (ID, NAME, NAME_ES)
SELECT INV_LKUP_RESPONSIBLE_TYPE_SEQ.nextval, 'Responsable manteniment', 'Responsable de mantenimiento'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM INV_LKUP_RESPONSIBLE_TYPE WHERE NAME = 'Responsable manteniment');

INSERT INTO INV_APP_RESPONSIBLE_AUTHORIZED (ID, APPLICATION_ID, CREATED_AT, CREATED_BY)
SELECT INV_APP_RESPONSIBLE_AUTHORIZED_SEQ.nextval, a.APP_APPLICATION_ID, SYSTIMESTAMP, 'ADMIN'
FROM INV_APPLICATION a
WHERE NOT EXISTS (SELECT 1 FROM INV_APP_RESPONSIBLE_AUTHORIZED r WHERE r.APPLICATION_ID = a.APP_APPLICATION_ID);

INSERT INTO INV_APP_RESPONSIBLE_AUTHORIZED_AUD (AUDIT_ID, APP_RESPONSIBLE_AUTHORIZED_ID, APPLICATION_ID, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_APP_RESPONSIBLE_AUTHORIZED_AUD_SEQ.nextval, r.ID, r.APPLICATION_ID, r.CREATED_AT, r.CREATED_BY, 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM INV_APP_RESPONSIBLE_AUTHORIZED r
WHERE NOT EXISTS (SELECT 1 FROM INV_APP_RESPONSIBLE_AUTHORIZED_AUD ra WHERE ra.APP_RESPONSIBLE_AUTHORIZED_ID = r.ID AND ra.AUD_ACTION = 'INSERT');

INSERT INTO INV_APP_INFORMATION_SYSTEM_DB (ID, APPLICATION_ID, CREATED_AT, CREATED_BY)
SELECT INV_APP_INF_SYS_DB_SEQ.nextval, a.APP_APPLICATION_ID, SYSTIMESTAMP, 'ADMIN'
FROM INV_APPLICATION a
WHERE NOT EXISTS (SELECT 1 FROM INV_APP_INFORMATION_SYSTEM_DB s WHERE s.APPLICATION_ID = a.APP_APPLICATION_ID);

INSERT INTO INV_APP_INFORMATION_SYSTEM_DB_AUD (AUDIT_ID, ID, APPLICATION_ID, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_APP_INF_SYS_DB_AUD_SEQ.nextval, s.ID, s.APPLICATION_ID, s.CREATED_AT, s.CREATED_BY, 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM INV_APP_INFORMATION_SYSTEM_DB s
WHERE NOT EXISTS (SELECT 1 FROM INV_APP_INFORMATION_SYSTEM_DB_AUD sa WHERE sa.ID = s.ID AND sa.AUD_ACTION = 'INSERT');

INSERT INTO INV_APP_DEVELOPMENT (ID, APPLICATION_ID, CREATED_AT, CREATED_BY)
SELECT INV_APP_DEVELOPMENT_SEQ.nextval, a.APP_APPLICATION_ID, SYSTIMESTAMP, 'ADMIN'
FROM INV_APPLICATION a
WHERE NOT EXISTS (SELECT 1 FROM INV_APP_DEVELOPMENT d WHERE d.APPLICATION_ID = a.APP_APPLICATION_ID);

INSERT INTO INV_APP_DEVELOPMENT_AUD (AUDIT_ID, APP_DEVELOPMENT_ID, APPLICATION_ID, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_APP_DEVELOPMENT_AUD_SEQ.nextval, d.ID, d.APPLICATION_ID, d.CREATED_AT, d.CREATED_BY, 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM INV_APP_DEVELOPMENT d
WHERE NOT EXISTS (SELECT 1 FROM INV_APP_DEVELOPMENT_AUD da WHERE da.APP_DEVELOPMENT_ID = d.ID AND da.AUD_ACTION = 'INSERT');

-- Sample AppResponsible row on the first available Responsables tab anchor, so INV_APP_RESPONSIBLE
-- (and its audit trail) is not left empty after a fresh install. Uses "Responsable del servei"
-- rather than "Responsable de la informació", since the seeded sample person is not Personal CAIB.
INSERT INTO INV_APP_RESPONSIBLE (ID, APP_RESPONSIBLE_AUTHORIZED_ID, PERSON_ID, RESPONSIBLE_TYPE_ID, JOB_TITLE, CREATED_AT, CREATED_BY)
SELECT INV_APP_RESPONSIBLE_SEQ.nextval,
       r.ID,
       (SELECT ID FROM INV_PERSON WHERE EMAIL = 'joan.puig@plexus.example'),
       (SELECT ID FROM INV_LKUP_RESPONSIBLE_TYPE WHERE NAME = 'Responsable del servei'),
       'Cap de projecte',
       SYSTIMESTAMP, 'ADMIN'
FROM INV_APP_RESPONSIBLE_AUTHORIZED r
WHERE r.ID = (SELECT MIN(ID) FROM INV_APP_RESPONSIBLE_AUTHORIZED)
  AND NOT EXISTS (
      SELECT 1 FROM INV_APP_RESPONSIBLE ar
      WHERE ar.APP_RESPONSIBLE_AUTHORIZED_ID = r.ID
        AND ar.RESPONSIBLE_TYPE_ID = (SELECT ID FROM INV_LKUP_RESPONSIBLE_TYPE WHERE NAME = 'Responsable del servei')
  );

INSERT INTO INV_APP_RESPONSIBLE_AUD (AUDIT_ID, APP_RESPONSIBLE_ID, APP_RESPONSIBLE_AUTHORIZED_ID, PERSON_ID, RESPONSIBLE_TYPE_ID, JOB_TITLE, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_APP_RESPONSIBLE_AUD_SEQ.nextval, ar.ID, ar.APP_RESPONSIBLE_AUTHORIZED_ID, ar.PERSON_ID, ar.RESPONSIBLE_TYPE_ID, ar.JOB_TITLE, ar.CREATED_AT, ar.CREATED_BY, 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM INV_APP_RESPONSIBLE ar
WHERE NOT EXISTS (SELECT 1 FROM INV_APP_RESPONSIBLE_AUD ara WHERE ara.APP_RESPONSIBLE_ID = ar.ID AND ara.AUD_ACTION = 'INSERT');

INSERT INTO INV_APP_AUTHORIZED (ID, APP_RESPONSIBLE_AUTHORIZED_ID, PERSON_ID, CREATED_AT, CREATED_BY)
SELECT INV_APP_AUTHORIZED_SEQ.nextval,
       r.ID,
       (SELECT ID FROM INV_PERSON WHERE EMAIL = 'joan.puig@plexus.example'),
       SYSTIMESTAMP, 'ADMIN'
FROM INV_APP_RESPONSIBLE_AUTHORIZED r
WHERE r.ID = (SELECT MIN(ID) FROM INV_APP_RESPONSIBLE_AUTHORIZED)
  AND NOT EXISTS (
      SELECT 1 FROM INV_APP_AUTHORIZED aa
      WHERE aa.APP_RESPONSIBLE_AUTHORIZED_ID = r.ID
        AND aa.PERSON_ID = (SELECT ID FROM INV_PERSON WHERE EMAIL = 'joan.puig@plexus.example')
  );

INSERT INTO INV_APP_AUTHORIZED_AUD (AUDIT_ID, APP_AUTHORIZED_ID, APP_RESPONSIBLE_AUTHORIZED_ID, PERSON_ID, CREATED_AT, CREATED_BY, AUD_ACTION, AUDIT_DATE, AUDIT_USER)
SELECT INV_APP_AUTHORIZED_AUD_SEQ.nextval, aa.ID, aa.APP_RESPONSIBLE_AUTHORIZED_ID, aa.PERSON_ID, aa.CREATED_AT, aa.CREATED_BY, 'INSERT', SYSTIMESTAMP, 'ADMIN'
FROM INV_APP_AUTHORIZED aa
WHERE NOT EXISTS (SELECT 1 FROM INV_APP_AUTHORIZED_AUD aaa WHERE aaa.APP_AUTHORIZED_ID = aa.ID AND aaa.AUD_ACTION = 'INSERT');

INSERT INTO INV_APP_AUTHORIZED_TYPE_LINK (ID, APP_AUTHORIZED_ID, AUTHORIZATION_TYPE_ID)
SELECT INV_APP_AUTHORIZED_TYPE_LINK_SEQ.nextval,
       aa.ID,
       (SELECT ID FROM INV_AUTHORIZATION_TYPE WHERE NAME_ES = 'Firmar peticiones')
FROM INV_APP_AUTHORIZED aa
WHERE aa.APP_RESPONSIBLE_AUTHORIZED_ID = (SELECT MIN(ID) FROM INV_APP_RESPONSIBLE_AUTHORIZED)
  AND aa.PERSON_ID = (SELECT ID FROM INV_PERSON WHERE EMAIL = 'joan.puig@plexus.example')
  AND NOT EXISTS (
      SELECT 1 FROM INV_APP_AUTHORIZED_TYPE_LINK l
      WHERE l.APP_AUTHORIZED_ID = aa.ID
        AND l.AUTHORIZATION_TYPE_ID = (SELECT ID FROM INV_AUTHORIZATION_TYPE WHERE NAME_ES = 'Firmar peticiones')
  );

COMMIT;
