import { HttpErrorResponse } from '@angular/common/http';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { ActivatedRoute, Router } from '@angular/router';
import { CommissionType } from '@features/commissions/commissions.model';
import { MessageService } from 'primeng/api';
import { of, throwError } from 'rxjs';

import { ApplicationStatus } from '../../applications.model';
import { ApplicationCreateFormGroup } from '../../forms/application-form.factory';
import {
  ApplicationCommissionOption,
  ApplicationSelectOptions,
} from '../../services/application-options.service';
import { ApplicationsService } from '../../services/applications.service';
import { ApplicationCreateForm } from './application-create-form';

class ResizeObserverMock implements ResizeObserver {
  disconnect(): void {}
  observe(): void {}
  unobserve(): void {}
}

globalThis.ResizeObserver ??= ResizeObserverMock;

const OPTIONS: ApplicationSelectOptions = {
  categories: [{ label: 'DRASSANA', value: 1 }],
  informationSystems: [{ label: 'Instrumental', value: 2 }],
  scopes: [{ label: 'Departamental', value: 3 }],
  commissions: [
    {
      label: 'Comissió tècnica',
      value: 4,
      expedientNumber: 'EXP-4',
      approvalDate: '2026-07-14',
      commissionType: CommissionType.TECNICA,
    },
  ],
  administrativeUnits: [{ label: 'DGEDOT', value: 5 }],
};

describe('ApplicationCreateForm', () => {
  let fixture: ComponentFixture<ApplicationCreateForm>;
  let formComponent: {
    form: ApplicationCreateFormGroup;
    selectCommission: (commission: ApplicationCommissionOption | null) => void;
    submit: () => void;
  };
  let messageService: MessageService;
  let create: ReturnType<typeof vi.fn>;
  const route = {};
  const router = { navigate: vi.fn() };

  beforeEach(async () => {
    router.navigate.mockReset();
    create = vi.fn(() => of({ id: 1 }));

    await TestBed.configureTestingModule({
      imports: [ApplicationCreateForm],
      providers: [
        MessageService,
        { provide: ActivatedRoute, useValue: route },
        { provide: ApplicationsService, useValue: { create } },
        { provide: Router, useValue: router },
      ],
    }).compileComponents();

    fixture = TestBed.createComponent(ApplicationCreateForm);
    fixture.componentRef.setInput('options', OPTIONS);
    formComponent = fixture.componentInstance as unknown as typeof formComponent;
    messageService = TestBed.inject(MessageService);
    fixture.detectChanges();
  });

  it('marks invalid controls and exposes accessible errors without navigating', () => {
    const addSpy = vi.spyOn(messageService, 'add');

    formComponent.submit();
    fixture.detectChanges();

    const applicationInput = fixture.nativeElement.querySelector(
      '#create-application-application',
    ) as HTMLInputElement;

    expect(formComponent.form.controls.application.touched).toBe(true);
    expect(applicationInput.getAttribute('aria-invalid')).toBe('true');
    expect(applicationInput.getAttribute('aria-describedby')).toBe(
      'create-application-application-error',
    );
    expect(create).not.toHaveBeenCalled();
    expect(addSpy).not.toHaveBeenCalled();
    expect(router.navigate).not.toHaveBeenCalled();
  });

  it('submits a valid form to the server and navigates back to the list', () => {
    const addSpy = vi.spyOn(messageService, 'add');

    formComponent.form.patchValue({
      application: 'Invai',
      category: 1,
      informationSystem: 2,
      scope: 3,
      commission: 4,
      prefix: 'CVF',
      code: '0001',
      administrativeUnit: 5,
      description: '',
    });

    formComponent.submit();

    expect(create).toHaveBeenCalledWith({
      name: 'Invai',
      prefix: 'CVF',
      code: '0001',
      categoryId: 1,
      systemTypeId: 2,
      fieldId: 3,
      admUnitId: 5,
      commissionId: 4,
      description: '',
      statusId: ApplicationStatus.ACTIVE,
    });
    expect(addSpy).toHaveBeenCalledWith(expect.objectContaining({ severity: 'success' }));
    expect(router.navigate).toHaveBeenCalledWith(['..'], { relativeTo: route });
  });

  it('submits the HTML generated by the rich text description editor', () => {
    formComponent.form.patchValue({
      application: 'Invai',
      category: 1,
      informationSystem: 2,
      scope: 3,
      commission: 4,
      prefix: 'CVF',
      code: '0001',
      administrativeUnit: 5,
      description: '<p>Descripció amb <strong>format</strong></p>',
    });

    formComponent.submit();

    expect(create).toHaveBeenCalledWith(
      expect.objectContaining({
        description: '<p>Descripció amb <strong>format</strong></p>',
      }),
    );
  });

  it('submits visually empty rich text descriptions as an empty string', () => {
    formComponent.form.patchValue({
      application: 'Invai',
      category: 1,
      informationSystem: 2,
      scope: 3,
      commission: 4,
      prefix: 'CVF',
      code: '0001',
      administrativeUnit: 5,
      description: '<p><br></p><p>&nbsp;</p>',
    });

    formComponent.submit();

    expect(create).toHaveBeenCalledWith(
      expect.objectContaining({
        description: '',
      }),
    );
  });

  it('does not submit an application code shorter than four characters', () => {
    formComponent.form.patchValue({
      application: 'Invai',
      category: 1,
      informationSystem: 2,
      scope: 3,
      commission: 4,
      prefix: 'CVF',
      code: '123',
      administrativeUnit: 5,
      description: '',
    });

    formComponent.submit();
    fixture.detectChanges();

    const codeInput = fixture.nativeElement.querySelector(
      '#create-application-code',
    ) as HTMLInputElement;
    const codeError = fixture.nativeElement.querySelector('#create-application-code-error');

    expect(formComponent.form.controls.code.touched).toBe(true);
    expect(codeInput.getAttribute('aria-invalid')).toBe('true');
    expect(codeInput.getAttribute('aria-describedby')).toBe('create-application-code-error');
    expect(codeError?.textContent.trim()).toBe('El codi ha de tenir com a mínim 4 caràcters');
    expect(create).not.toHaveBeenCalled();
    expect(router.navigate).not.toHaveBeenCalled();
  });

  it.each([
    {
      field: 'prefix' as const,
      value: 'INVAI',
      error: 'El prefix ha de tenir com a màxim 3 caràcters',
    },
    {
      field: 'code' as const,
      value: '12345678901',
      error: 'El codi ha de tenir com a màxim 10 caràcters',
    },
  ])('does not submit when $field exceeds its maximum length', ({ field, value, error }) => {
    formComponent.form.patchValue({
      application: 'Invai',
      category: 1,
      informationSystem: 2,
      scope: 3,
      commission: 4,
      prefix: 'CVF',
      code: '0001',
      administrativeUnit: 5,
      description: '',
    });
    formComponent.form.controls[field].setValue(value);

    formComponent.submit();
    fixture.detectChanges();

    const input = fixture.nativeElement.querySelector(
      `#create-application-${field}`,
    ) as HTMLInputElement;
    const validationError = fixture.nativeElement.querySelector(
      `#create-application-${field}-error`,
    );

    expect(formComponent.form.controls[field].touched).toBe(true);
    expect(input.getAttribute('aria-invalid')).toBe('true');
    expect(input.getAttribute('aria-describedby')).toBe(`create-application-${field}-error`);
    expect(validationError?.textContent.trim()).toBe(error);
    expect(create).not.toHaveBeenCalled();
    expect(router.navigate).not.toHaveBeenCalled();
  });

  it('shows an error and stays on the form when creating fails', () => {
    const addSpy = vi.spyOn(messageService, 'add');
    create.mockReturnValueOnce(throwError(() => new Error('Request failed')));

    formComponent.form.patchValue({
      application: 'Invai',
      category: 1,
      informationSystem: 2,
      scope: 3,
      commission: 4,
      prefix: 'CVF',
      code: '0001',
      administrativeUnit: 5,
      description: 'Desc',
    });

    formComponent.submit();

    expect(addSpy).toHaveBeenCalledWith({
      severity: 'error',
      summary: 'Error',
      detail: "No s'ha pogut afegir l'aplicació.",
    });
    expect(router.navigate).not.toHaveBeenCalled();
  });

  it('does not duplicate the global dialog with a toast for a structured bad request', () => {
    const addSpy = vi.spyOn(messageService, 'add');
    create.mockReturnValueOnce(
      throwError(
        () =>
          new HttpErrorResponse({
            status: 400,
            error: {
              error: 'Error de validació',
              message: 'El prefix ja està assignat a una altra aplicació.',
            },
          }),
      ),
    );

    formComponent.form.patchValue({
      application: 'Invai',
      category: 1,
      informationSystem: 2,
      scope: 3,
      commission: 4,
      prefix: 'CVF',
      code: '0001',
      administrativeUnit: 5,
      description: 'Desc',
    });

    formComponent.submit();

    expect(addSpy).not.toHaveBeenCalled();
    expect(router.navigate).not.toHaveBeenCalled();
  });

  it('fills the read-only commission details from the selected option', () => {
    formComponent.selectCommission({
      label: 'Comissió tècnica',
      value: 4,
      expedientNumber: 'EXP-4',
      approvalDate: '2026-07-14',
      commissionType: CommissionType.TECNICA,
    });

    expect(formComponent.form.getRawValue()).toEqual(
      expect.objectContaining({
        commissionExpedientNumber: 'EXP-4',
        commissionApprovalDate: '2026-07-14',
        commissionType: CommissionType.TECNICA,
      }),
    );
    expect(formComponent.form.controls.commissionExpedientNumber.disabled).toBe(true);
    expect(formComponent.form.controls.commissionApprovalDate.disabled).toBe(true);
    expect(formComponent.form.controls.commissionType.disabled).toBe(true);
  });
});
